"""
Setup sheet generation for CNC machining.

This module generates comprehensive setup sheets with workpiece specifications,
work holding instructions, origin positioning, safety notes, and quality checkpoints.

Requirements: 6.2, 8.5
"""

from typing import Dict, Any
from pathlib import Path


def generate_setup_sheets(
    top_frame_toolpaths: Dict[str, Any],
    bottom_tray_toolpaths: Dict[str, Any],
    output_path: str = "output/60_percent_standard/cnc/setup"
) -> Dict[str, str]:
    """
    Generate setup sheets for both components.
    
    Args:
        top_frame_toolpaths: Top frame toolpaths dictionary
        bottom_tray_toolpaths: Bottom tray toolpaths dictionary
        output_path: Output directory path
        
    Returns:
        Dictionary mapping component names to file paths
        
    Requirements: 6.2, 8.5
    """
    # Create output directory
    output_dir = Path(output_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate top frame setup sheet
    top_frame_content = _generate_top_frame_setup_sheet(top_frame_toolpaths)
    top_frame_path = output_dir / "setup_sheet_top_frame.md"
    with open(top_frame_path, 'w') as f:
        f.write(top_frame_content)
    
    # Generate bottom tray setup sheet
    bottom_tray_content = _generate_bottom_tray_setup_sheet(bottom_tray_toolpaths)
    bottom_tray_path = output_dir / "setup_sheet_bottom_tray.md"
    with open(bottom_tray_path, 'w') as f:
        f.write(bottom_tray_content)
    
    return {
        'top_frame': str(top_frame_path),
        'bottom_tray': str(bottom_tray_path)
    }


def _generate_top_frame_setup_sheet(toolpaths: Dict[str, Any]) -> str:
    """Generate setup sheet for top frame component."""
    lines = [
        "# CNC Setup Sheet: Top Frame",
        "",
        "## Component Overview",
        "",
        "- **Component:** Top Frame (Switch Plate Layer)",
        "- **Material:** Hardwood (walnut, maple, or cherry recommended)",
        "- **Final Dimensions:** 295mm x 105mm x 5mm",
        "- **Total Operations:** 5",
        "- **Estimated Machining Time:** ~45-60 minutes",
        "",
        "## Workpiece Specifications",
        "",
        "### Stock Material",
        "",
        "- **Material Type:** Hardwood",
        "- **Recommended Species:** Walnut, maple, cherry",
        "- **Stock Dimensions:** 295mm (L) x 105mm (W) x 6mm (H)",
        "- **Final Thickness:** 5mm (will be surfaced down)",
        "- **Grain Orientation:** Length-wise for maximum strength",
        "",
        "### Material Preparation",
        "",
        "1. **Surface Planing:**",
        "   - Plane both faces flat and parallel",
        "   - Target thickness: 6mm ±0.1mm",
        "   - Ensure faces are within 0.05mm of parallel",
        "",
        "2. **Inspection:**",
        "   - Check for knots, cracks, or defects",
        "   - Reject pieces with defects in mounting hole areas",
        "   - Verify grain runs length-wise",
        "",
        "3. **Conditioning:**",
        "   - Allow wood to acclimate to shop conditions",
        "   - Moisture content should be 6-8% for indoor use",
        "",
        "## Work Holding Instructions",
        "",
        "### Primary Setup (Operations 1, 3, 4, 5)",
        "",
        "**Method:** Double-sided tape or vacuum table",
        "",
        "- **Double-Sided Tape Method:**",
        "  1. Clean workpiece bottom surface thoroughly",
        "  2. Apply carpet tape in grid pattern (avoid toolpath areas)",
        "  3. Press firmly onto spoilboard or fixture plate",
        "  4. Ensure no air bubbles or gaps",
        "  5. Allow 10 minutes for adhesive to set",
        "",
        "- **Vacuum Table Method:**",
        "  1. Ensure workpiece bottom is flat and smooth",
        "  2. Place on vacuum table with even contact",
        "  3. Activate vacuum (minimum 15 inHg)",
        "  4. Verify secure hold before starting",
        "",
        "### Secondary Setup (Operation 2 - Brass Insert Counterbores)",
        "",
        "**Method:** Flip and re-secure",
        "",
        "1. Complete operations 1, 3, 4, 5 first",
        "2. Carefully remove workpiece from primary setup",
        "3. Flip workpiece (bottom face up)",
        "4. Re-secure using same method as primary setup",
        "5. Re-zero Z-axis on new top surface",
        "6. Machine brass insert counterbores from bottom",
        "",
        "**Note:** Brass insert counterbores are machined from the bottom surface and require a workpiece flip.",
        "",
        "## Origin Positioning",
        "",
        "### Coordinate System",
        "",
        "- **Origin Location:** Top-left corner of case external profile, top surface",
        "- **X-Axis:** Positive to the right (length direction)",
        "- **Y-Axis:** Positive downward (width direction)",
        "- **Z-Axis:** Positive downward (depth into material)",
        "",
        "### Setting the Origin",
        "",
        "1. **X and Y Zero:**",
        "   - Use edge finder or probe to locate top-left corner",
        "   - Set X=0, Y=0 at this corner",
        "   - Verify position with test probe",
        "",
        "2. **Z Zero:**",
        "   - Touch off on top surface of workpiece",
        "   - Set Z=0 at top surface",
        "   - Use paper method or touch probe for accuracy",
        "",
        "3. **Verification:**",
        "   - Jog to known positions to verify origin",
        "   - Check that all features will be within stock boundaries",
        "",
        "## Operation Sequence",
        "",
        "### Operation 1: Face Surfacing",
        "- **Tool:** 6mm flat endmill",
        "- **Depth:** 0.5mm",
        "- **Purpose:** Create flat reference surface",
        "- **Notes:** Ensures consistent 5mm final thickness",
        "",
        "### Operation 2: Brass Insert Counterbores (6x)",
        "- **Tool:** 6mm flat endmill",
        "- **Depth:** 4mm from bottom surface",
        "- **Diameter:** 5.8mm",
        "- **Notes:** Requires workpiece flip, critical ±0.1mm tolerance",
        "",
        "### Operation 3: PCB Opening Pocket",
        "- **Roughing Tool:** 6mm flat endmill",
        "- **Finishing Tool:** 3mm flat endmill",
        "- **Depth:** Through full 5mm thickness",
        "- **Dimensions:** 286mm x 95.6mm",
        "- **Notes:** Critical ±0.1mm tolerance, through-pocket",
        "",
        "### Operation 4: USB Cutout",
        "- **Tool:** 3mm flat endmill",
        "- **Depth:** Through full 5mm thickness",
        "- **Dimensions:** 16mm x 10mm with 1mm corner radius",
        "- **Notes:** Centered on top edge, through-cutout",
        "",
        "### Operation 5: External Profile",
        "- **Roughing Tool:** 6mm flat endmill",
        "- **Finishing Tool:** 3mm flat endmill",
        "- **Depth:** Through full 5mm thickness",
        "- **Notes:** Includes tabs for workpiece retention, 3mm corner radius",
        "",
        "## Safety Notes",
        "",
        "### Before Starting",
        "",
        "- [ ] Verify all tools are sharp and in good condition",
        "- [ ] Check work holding is secure (no movement)",
        "- [ ] Confirm origin is set correctly",
        "- [ ] Verify toolpaths are loaded correctly",
        "- [ ] Check spindle rotation direction",
        "- [ ] Ensure adequate dust collection",
        "- [ ] Wear safety glasses and hearing protection",
        "",
        "### During Machining",
        "",
        "- [ ] Monitor first pass of each operation closely",
        "- [ ] Listen for unusual sounds (tool chatter, binding)",
        "- [ ] Watch for excessive heat or smoke",
        "- [ ] Verify chip evacuation is adequate",
        "- [ ] Do not reach into cutting area while spindle is running",
        "- [ ] Pause machine if any issues arise",
        "",
        "### After Machining",
        "",
        "- [ ] Allow spindle to stop completely before removing workpiece",
        "- [ ] Carefully remove tabs with flush-cut saw",
        "- [ ] Inspect all features for quality",
        "- [ ] Clean machine and work area",
        "",
        "## Quality Checkpoints",
        "",
        "### Dimensional Checks",
        "",
        "- [ ] **External Dimensions:** 295mm x 105mm (±0.2mm)",
        "- [ ] **Thickness:** 5mm (±0.1mm after surfacing)",
        "- [ ] **PCB Opening:** 286mm x 95.6mm (±0.1mm critical)",
        "- [ ] **Brass Insert Holes:** 5.8mm diameter (±0.1mm critical)",
        "- [ ] **Brass Insert Hole Positions:** Match specification (±0.1mm critical)",
        "- [ ] **USB Cutout:** 16mm x 10mm (±0.2mm)",
        "- [ ] **Corner Radii:** 3mm external, 1mm USB cutout (±0.2mm)",
        "",
        "### Visual Inspection",
        "",
        "- [ ] No visible cracks, splits, or defects",
        "- [ ] Clean edges with no tear-out",
        "- [ ] Smooth surfaces (no tool marks)",
        "- [ ] Brass insert holes clean and perpendicular",
        "- [ ] Corner radii consistent and smooth",
        "",
        "### Functional Testing",
        "",
        "- [ ] PCB fits in opening with 0.5mm clearance per side",
        "- [ ] USB cable inserts smoothly through cutout",
        "- [ ] Brass inserts press-fit into counterbores",
        "- [ ] No sharp edges or splinters",
        "",
        "## Troubleshooting",
        "",
        "### Common Issues",
        "",
        "**Issue:** Tear-out on edges",
        "- **Cause:** Dull tool or incorrect feed direction",
        "- **Solution:** Use sharp tools, climb milling, backing board",
        "",
        "**Issue:** Brass insert holes too tight",
        "- **Cause:** Tool deflection or incorrect offset",
        "- **Solution:** Verify tool diameter, check machine calibration",
        "",
        "**Issue:** PCB opening too small",
        "- **Cause:** Incorrect tool radius compensation",
        "- **Solution:** Verify CAM settings, re-machine with adjusted offset",
        "",
        "**Issue:** Workpiece movement during cutting",
        "- **Cause:** Inadequate work holding",
        "- **Solution:** Improve clamping, reduce feed rates, check vacuum pressure",
        "",
        "## Notes",
        "",
        "- Complete operations 1, 3, 4, 5 before flipping for operation 2",
        "- Brass insert counterbores require careful alignment after flip",
        "- Through-cutting operations (3, 4, 5) require secure work holding",
        "- Save tabs on external profile for last to maintain workpiece stability",
        "- Document any deviations from standard procedure",
        ""
    ]
    
    return '\n'.join(lines)


def _generate_bottom_tray_setup_sheet(toolpaths: Dict[str, Any]) -> str:
    """Generate setup sheet for bottom tray component."""
    lines = [
        "# CNC Setup Sheet: Bottom Tray",
        "",
        "## Component Overview",
        "",
        "- **Component:** Bottom Tray (Base with Cavity)",
        "- **Material:** Hardwood (walnut, maple, or cherry recommended)",
        "- **Final Dimensions:** 295mm x 105mm x 15mm",
        "- **Total Operations:** 7",
        "- **Estimated Machining Time:** ~90-120 minutes",
        "",
        "## Workpiece Specifications",
        "",
        "### Stock Material",
        "",
        "- **Material Type:** Hardwood",
        "- **Recommended Species:** Walnut, maple, cherry",
        "- **Stock Dimensions:** 295mm (L) x 105mm (W) x 20mm (H)",
        "- **Final Thickness:** 15mm (will be surfaced down)",
        "- **Grain Orientation:** Length-wise for maximum strength",
        "",
        "### Material Preparation",
        "",
        "1. **Surface Planing:**",
        "   - Plane both faces flat and parallel",
        "   - Target thickness: 20mm ±0.2mm",
        "   - Ensure faces are within 0.1mm of parallel",
        "",
        "2. **Inspection:**",
        "   - Check for knots, cracks, or defects",
        "   - Reject pieces with defects in mounting or structural areas",
        "   - Verify grain runs length-wise",
        "",
        "3. **Conditioning:**",
        "   - Allow wood to acclimate to shop conditions",
        "   - Moisture content should be 6-8% for indoor use",
        "",
        "## Work Holding Instructions",
        "",
        "### Primary Setup (Operations 1, 5, 6, 7)",
        "",
        "**Method:** Clamps or fixture plate",
        "",
        "- **Clamping Method:**",
        "  1. Use toe clamps or cam clamps on edges",
        "  2. Position clamps outside toolpath areas",
        "  3. Ensure workpiece sits flat on spoilboard",
        "  4. Tighten clamps evenly to prevent warping",
        "  5. Verify no movement before starting",
        "",
        "- **Fixture Plate Method:**",
        "  1. Secure workpiece to fixture with screws in waste areas",
        "  2. Ensure screws are below surface level",
        "  3. Verify fixture is square to machine axes",
        "",
        "### Secondary Setup (Operations 2, 3, 4)",
        "",
        "**Method:** Flip and re-secure",
        "",
        "1. Complete operations 1, 5, 6, 7 first",
        "2. Carefully remove workpiece from primary setup",
        "3. Flip workpiece (bottom face up)",
        "4. Re-secure using clamps or fixture",
        "5. Re-zero Z-axis on new top surface",
        "6. Machine rubber feet recesses, counterbores, and through-holes",
        "",
        "**Note:** Operations 2, 3, 4 are machined from the bottom surface and require a workpiece flip.",
        "",
        "## Origin Positioning",
        "",
        "### Coordinate System",
        "",
        "- **Origin Location:** Top-left corner of case external profile, top surface",
        "- **X-Axis:** Positive to the right (length direction)",
        "- **Y-Axis:** Positive downward (width direction)",
        "- **Z-Axis:** Positive downward (depth into material)",
        "",
        "### Setting the Origin",
        "",
        "1. **X and Y Zero:**",
        "   - Use edge finder or probe to locate top-left corner",
        "   - Set X=0, Y=0 at this corner",
        "   - Verify position with test probe",
        "",
        "2. **Z Zero:**",
        "   - Touch off on top surface of workpiece",
        "   - Set Z=0 at top surface",
        "   - Use paper method or touch probe for accuracy",
        "",
        "3. **Verification:**",
        "   - Jog to known positions to verify origin",
        "   - Check that all features will be within stock boundaries",
        "   - Verify standoff pillar positions align with mounting holes",
        "",
        "## Operation Sequence",
        "",
        "### Operation 1: Face Surfacing",
        "- **Tool:** 6mm flat endmill",
        "- **Depth:** 0.5mm",
        "- **Purpose:** Create flat reference surface",
        "- **Notes:** Ensures consistent thickness and flat top surface",
        "",
        "### Operation 2: Rubber Feet Recesses (4x)",
        "- **Tool:** 10mm flat endmill",
        "- **Depth:** 2mm from bottom surface",
        "- **Diameter:** 10mm",
        "- **Notes:** Requires workpiece flip, positioned 10mm from corners",
        "",
        "### Operation 3: Assembly Screw Counterbores (6x)",
        "- **Tool:** 6mm flat endmill",
        "- **Depth:** 3mm from bottom surface",
        "- **Diameter:** 6mm",
        "- **Notes:** Requires workpiece flip, concentric with mounting holes",
        "",
        "### Operation 4: Assembly Screw Through-Holes (6x)",
        "- **Tool:** 3.2mm drill",
        "- **Depth:** Through full 15mm thickness",
        "- **Diameter:** 3.2mm (M3 clearance)",
        "- **Notes:** Requires workpiece flip, peck drilling recommended",
        "",
        "### Operation 5: Internal Cavity Pocket",
        "- **Roughing Tool:** 6mm flat endmill",
        "- **Finishing Tool:** 4mm flat endmill",
        "- **Depth:** 8mm from top surface",
        "- **Dimensions:** 287mm x 96.6mm",
        "- **Notes:** Leaves 6mm standoff pillars, 2mm corner radius",
        "",
        "### Operation 6: Standoff Through-Holes (6x)",
        "- **Tool:** 2.2mm drill",
        "- **Depth:** Through standoff pillars",
        "- **Diameter:** 2.2mm (M2 clearance)",
        "- **Notes:** Critical ±0.1mm tolerance, peck drilling recommended",
        "",
        "### Operation 7: External Profile",
        "- **Roughing Tool:** 6mm flat endmill",
        "- **Finishing Tool:** 3mm flat endmill",
        "- **Depth:** Through full 15mm thickness",
        "- **Notes:** Includes tabs for workpiece retention, 3mm corner radius",
        "",
        "## Safety Notes",
        "",
        "### Before Starting",
        "",
        "- [ ] Verify all tools are sharp and in good condition",
        "- [ ] Check work holding is secure (no movement)",
        "- [ ] Confirm origin is set correctly",
        "- [ ] Verify toolpaths are loaded correctly",
        "- [ ] Check spindle rotation direction",
        "- [ ] Ensure adequate dust collection",
        "- [ ] Wear safety glasses and hearing protection",
        "- [ ] Verify drill bits are properly secured in collet",
        "",
        "### During Machining",
        "",
        "- [ ] Monitor first pass of each operation closely",
        "- [ ] Listen for unusual sounds (tool chatter, binding)",
        "- [ ] Watch for excessive heat or smoke",
        "- [ ] Verify chip evacuation is adequate (especially in cavity)",
        "- [ ] Do not reach into cutting area while spindle is running",
        "- [ ] Pause machine if any issues arise",
        "- [ ] Check drill bit condition after deep holes",
        "",
        "### After Machining",
        "",
        "- [ ] Allow spindle to stop completely before removing workpiece",
        "- [ ] Carefully remove tabs with flush-cut saw",
        "- [ ] Inspect all features for quality",
        "- [ ] Clean machine and work area",
        "- [ ] Remove chips from cavity and holes",
        "",
        "## Quality Checkpoints",
        "",
        "### Dimensional Checks",
        "",
        "- [ ] **External Dimensions:** 295mm x 105mm (±0.2mm)",
        "- [ ] **Thickness:** 15mm (±0.2mm after surfacing)",
        "- [ ] **Cavity Dimensions:** 287mm x 96.6mm (±0.2mm)",
        "- [ ] **Cavity Depth:** 8mm (±0.2mm)",
        "- [ ] **Standoff Pillar Diameter:** 6mm (±0.1mm)",
        "- [ ] **Standoff Pillar Height:** 3mm from cavity floor (±0.1mm)",
        "- [ ] **Standoff Holes:** 2.2mm diameter (±0.1mm critical)",
        "- [ ] **Assembly Screw Holes:** 3.2mm diameter (±0.2mm)",
        "- [ ] **Counterbore Depth:** 3mm (±0.2mm)",
        "- [ ] **Rubber Feet Recesses:** 10mm diameter, 2mm deep (±0.2mm)",
        "- [ ] **Corner Radii:** 3mm external, 2mm internal (±0.2mm)",
        "",
        "### Visual Inspection",
        "",
        "- [ ] No visible cracks, splits, or defects",
        "- [ ] Clean edges with no tear-out",
        "- [ ] Smooth surfaces in cavity (no tool marks)",
        "- [ ] Standoff pillars clean and perpendicular",
        "- [ ] All holes clean and free of burrs",
        "- [ ] Corner radii consistent and smooth",
        "- [ ] Counterbores concentric with through-holes",
        "",
        "### Functional Testing",
        "",
        "- [ ] Cavity accommodates PCB with clearance",
        "- [ ] Standoff holes accept M2 screws smoothly",
        "- [ ] Assembly screw holes accept M3 screws smoothly",
        "- [ ] Counterbores allow screw heads to sit flush",
        "- [ ] Rubber feet fit in recesses",
        "- [ ] No sharp edges or splinters",
        "- [ ] Mates flush with top frame",
        "",
        "## Troubleshooting",
        "",
        "### Common Issues",
        "",
        "**Issue:** Tear-out in cavity corners",
        "- **Cause:** Dull tool or incorrect feed direction",
        "- **Solution:** Use sharp tools, reduce feed rate in corners",
        "",
        "**Issue:** Standoff pillars not uniform height",
        "- **Cause:** Uneven cavity depth or workpiece not flat",
        "- **Solution:** Verify Z-zero, check workpiece flatness, re-surface if needed",
        "",
        "**Issue:** Drill bits breaking in deep holes",
        "- **Cause:** Inadequate chip evacuation or excessive feed rate",
        "- **Solution:** Use peck drilling, reduce feed rate, clear chips frequently",
        "",
        "**Issue:** Counterbores not concentric with through-holes",
        "- **Cause:** Origin shift after flip or incorrect positioning",
        "- **Solution:** Verify origin after flip, use alignment pins if available",
        "",
        "**Issue:** Cavity walls not smooth",
        "- **Cause:** Tool deflection or incorrect finishing pass",
        "- **Solution:** Reduce depth per pass, ensure finishing tool is sharp",
        "",
        "## Notes",
        "",
        "- Complete operations 1, 5, 6, 7 before flipping for operations 2, 3, 4",
        "- Bottom surface operations require careful alignment after flip",
        "- Deep cavity requires good chip evacuation",
        "- Standoff pillars are critical for PCB mounting - verify dimensions carefully",
        "- Through-holes must align with counterbores - check concentricity",
        "- Save tabs on external profile for last to maintain workpiece stability",
        "- Document any deviations from standard procedure",
        ""
    ]
    
    return '\n'.join(lines)
