"""
Switch-converter OpenSCAD generator (Layer 3 of the ergogen integration —
see projects/switch_converter/ergogen_integration.md).

Ergogen is 2D/2.5D only, so the PG1350->PG1425 adapter's 3D geometry
(bezel walls, clip windows, floor pocket, routing slots) can't come out of
Ergogen. This generator closes the gap: it takes the same Layout model that
drives the Ergogen config and emits a standalone OpenSCAD file with the
adapter geometry (inlined from
projects/switch_converter/OpenSCAD/pg1350_to_pg1425_adapter.scad, v3)
instantiated at every converter-marked key position — with the exact
ergogen-consistent x/y/rotation.

Rendered parts (select via `part` in OpenSCAD / the Customizer):

  "adapter" — one adapter at the origin (sanity check / single print)
  "panel"   — Variant A: all adapters at true board positions, joined by
              thin snap-off sprue bars for one-shot printing. Snap apart
              and place each adapter on its PG1425 PCB position.
  "plate"   — Variant B: integrated converter plate. One printable part:
              a plate slab whose top is flush with the adapter tops,
              unioned with the full adapter bodies at converter positions
              (pocket, clip windows and routing slots preserved). Normal
              (non-converter) keys get standard switch cutouts. The plate
              itself provides Choc switch retention via the adapters'
              built-in 1.2mm bezels.

Coordinates match the Ergogen output: +y UP (KLE y negated), rotation
counter-clockwise (KLE angle negated), positions are physical key centers.
"""

from __future__ import annotations

import math
from typing import Any, Dict, List

from ..layout import Layout

DEFAULTS = {
    "plate_margin": 3.0,      # mm added around key footprints (plate part)
    "corner_radius": 3.0,     # mm, plate corner rounding
    "switch_cutout": 14.0,    # mm, cutout for NON-converter keys (plate part)
    "sprue_w": 2.0,           # mm, sprue bar width (panel part)
    "sprue_h": 0.8,           # mm, sprue bar thickness (panel part)
    "sprue_max_dist_u": 1.6,  # neighbors within this many key units get a sprue
}


def generate_converter_scad(layout: Layout, options: Dict[str, Any] | None = None) -> str:
    """Generate the standalone converter panel / integrated plate SCAD."""
    opts = dict(DEFAULTS)
    if options:
        opts.update(options)

    layout.assign_matrix()
    unit = layout.unit
    converters = layout.converters
    bounds = layout.bounds_mm()

    # Converter positions: [x_center, y_center, rotation_deg] in SCAD space
    # (+y up, ccw rotation) — identical conversion to the Ergogen generator.
    conv_rows: List[str] = []
    centers: List[tuple] = []
    for key in converters:
        cx, cy = key.center_mm(unit)
        centers.append((cx, -cy))
        conv_rows.append(f"  [{cx:.3f}, {-cy:.3f}, {-key.rotation_angle:.3f}]")

    # Non-converter keys (plate part needs their standard cutouts).
    normal_rows: List[str] = []
    for key in layout.switches:
        if key.converter:
            continue
        cx, cy = key.center_mm(unit)
        normal_rows.append(
            f"  [{cx:.3f}, {-cy:.3f}, {-key.rotation_angle:.3f}]")

    # Sprue pairs for the panel: neighboring converters within range.
    max_dist = opts["sprue_max_dist_u"] * unit
    sprue_rows: List[str] = []
    for i in range(len(centers)):
        for j in range(i + 1, len(centers)):
            (x1, y1), (x2, y2) = centers[i], centers[j]
            if math.hypot(x2 - x1, y2 - y1) <= max_dist:
                sprue_rows.append(
                    f"  [{x1:.3f}, {y1:.3f}, {x2:.3f}, {y2:.3f}]")

    stats = layout.stats()

    return f"""// {layout.name} — switch-converter panel / integrated plate
// Generated by kbforge (converter format).
// Converter positions: {len(converters)} of {stats['switch_count']} switches.
//
// Adapter geometry inlined from
// projects/switch_converter/OpenSCAD/pg1350_to_pg1425_adapter.scad (v3):
// a 15x15x5mm carrier that seats a Kailh Choc PG1350 switch onto a Kailh
// PG1425 "Choc X" PCB footprint. The top 1.2mm of its bezel walls act as
// the switch plate (clip windows included).
//
// Parts:
//   "adapter" - one adapter at the origin
//   "panel"   - all adapters at board positions, joined by snap-off sprues
//   "plate"   - integrated converter plate (adapters fused into one plate)

/* [Part Selection] */
part = "panel"; // [adapter, panel, plate]

/* [Panel] */
sprue_w = {opts['sprue_w']};
sprue_h = {opts['sprue_h']};
sprue_inset = 7.0;   // sprue endpoints this far from adapter centers

/* [Plate] */
plate_margin  = {opts['plate_margin']};
corner_radius = {opts['corner_radius']};
switch_cutout = {opts['switch_cutout']};   // cutout for non-converter keys

/* [Hidden] */
$fn = 48;

// Converter positions: [x_center, y_center, rotation_deg]  (y-up)
converters = [
{",\n".join(conv_rows)}
];

// Non-converter switch positions: [x_center, y_center, rotation_deg]
normal_keys = [
{",\n".join(normal_rows) if normal_rows else ""}
];

// Sprue pairs: [x1, y1, x2, y2]
sprues = [
{",\n".join(sprue_rows) if sprue_rows else ""}
];

// Layout extents (mm, y-up space)
layout_min = [{bounds['min_x']:.3f}, {-bounds['max_y']:.3f}];
layout_max = [{bounds['max_x']:.3f}, {-bounds['min_y']:.3f}];

// ==========================================================================
// PG1350 -> PG1425 ADAPTER (inlined from pg1350_to_pg1425_adapter.scad v3)
// z = 0 is the adapter's bottom face (sits on the PG1425 PCB);
// alignment pins extend below z = 0.
// ==========================================================================

pocket_clearance = 0.30;
hole_clearance   = 0.20;
post_clearance   = 0.15;
eps              = 0.10;

choc_body_xy         = 13.80;
choc_body_h          = 2.20;
choc_flange_xy       = 15.00;
choc_center_post_d   = 3.20;
choc_center_post_len = 2.65;
choc_side_post_d     = 1.90;
choc_side_post_x     = 5.50;
choc_pin1_pos        = [ 0.0, 5.9 ];
choc_pin2_pos        = [ 5.0, 3.8 ];

pg1425_align_hole_d    = 1.30;
pg1425_align_positions = [ [ 5.5, -5.5], [-5.5,  5.5] ];
pg1425_align_pin_h     = 1.40;
pg1425_pin1_pos        = [-3.4,  2.9];
pg1425_pin2_pos        = [-3.4, -2.0];

body_x  = choc_flange_xy;
body_y  = choc_flange_xy;
wall_t  = (choc_flange_xy - choc_body_xy - pocket_clearance) / 2;
wall_h  = choc_body_h;
floor_h = choc_center_post_len + 0.15;
body_h  = floor_h + wall_h;
adapter_corner_radius = 0.5;

plate_t       = 1.20;
clip_window_w = 6.0;
slot_w        = 1.4;

adapter_slots = [
    [ choc_pin1_pos, pg1425_pin1_pos ],
    [ choc_pin2_pos, [2.4, -3.0], pg1425_pin2_pos ],
];

module rounded_block(x, y, h, r) {{
    if (r > 0) {{
        linear_extrude(height = h)
            offset(r = r) offset(delta = -r)
                square([x, y], center = true);
    }} else {{
        translate([0, 0, h/2]) cube([x, y, h], center = true);
    }}
}}

module adapter_body() {{
    rounded_block(body_x, body_y, body_h, adapter_corner_radius);
}}

module choc_pocket() {{
    pocket_xy = choc_body_xy + pocket_clearance;
    translate([0, 0, floor_h])
        rounded_block(pocket_xy, pocket_xy, wall_h + eps, 0.3);
}}

module clip_windows() {{
    window_h = wall_h - plate_t + eps;
    for (sy = [-1, 1])
        translate([0, sy * (body_y/2 - wall_t/2), floor_h + window_h/2 - eps/2])
            cube([clip_window_w, wall_t + 2*eps, window_h], center = true);
}}

module through_hole(pos, d) {{
    translate([pos[0], pos[1], -eps])
        cylinder(h = floor_h + 2*eps, d = d + hole_clearance);
}}

module pg1350_holes() {{
    through_hole([0, 0], choc_center_post_d);
    through_hole([-choc_side_post_x, 0], choc_side_post_d);
    through_hole([ choc_side_post_x, 0], choc_side_post_d);
}}

module routing_slot(pts) {{
    translate([0, 0, -eps])
        linear_extrude(height = floor_h + 2*eps)
            for (i = [0 : len(pts) - 2])
                hull() {{
                    translate(pts[i])     circle(d = slot_w);
                    translate(pts[i + 1]) circle(d = slot_w);
                }}
}}

module pin_routing_slots() {{
    for (s = adapter_slots) routing_slot(s);
}}

module pg1425_alignment_pins() {{
    for (p = pg1425_align_positions)
        translate([p[0], p[1], -pg1425_align_pin_h])
            cylinder(h = pg1425_align_pin_h + eps,
                     d = pg1425_align_hole_d - post_clearance);
}}

module adapter(with_pins = true) {{
    union() {{
        difference() {{
            adapter_body();
            choc_pocket();
            clip_windows();
            pg1350_holes();
            pin_routing_slots();
        }}
        if (with_pins) pg1425_alignment_pins();
    }}
}}

// ==========================================================================
// PANEL (Variant A): adapters at true board positions + snap-off sprues
// ==========================================================================

module placed_adapters(with_pins = true) {{
    for (c = converters)
        translate([c[0], c[1], 0])
            rotate([0, 0, c[2]])
                adapter(with_pins);
}}

module sprue_bars() {{
    // Thin bars spanning the gaps between neighboring adapter bodies,
    // overlapping ~0.5mm into each solid floor for adhesion. Snap or cut
    // them off after printing.
    linear_extrude(height = sprue_h)
        for (s = sprues) {{
            dx = s[2] - s[0];
            dy = s[3] - s[1];
            d  = norm([dx, dy]);
            ux = dx / d;
            uy = dy / d;
            hull() {{
                translate([s[0] + ux*sprue_inset, s[1] + uy*sprue_inset])
                    circle(d = sprue_w);
                translate([s[2] - ux*sprue_inset, s[3] - uy*sprue_inset])
                    circle(d = sprue_w);
            }}
        }}
}}

module panel() {{
    placed_adapters(with_pins = true);
    sprue_bars();
}}

// ==========================================================================
// INTEGRATED PLATE (Variant B): plate slab fused with the adapters
//
// Slab spans z = body_h - plate_t .. body_h, so its top is flush with the
// adapter tops and the Choc flanges rest on it. At converter positions the
// slab opens to the adapter pocket (the bezel walls merge seamlessly with
// the slab); the clip windows sit BELOW the slab, so they stay functional.
// Non-converter keys get standard switch cutouts (note: the slab sits at
// the converter-stack height — mixing in normal plate-mount switches only
// makes sense if their PCB is raised to match).
// ==========================================================================

module plate_outline_2d() {{
    minkowski() {{
        translate([layout_min[0] - plate_margin + corner_radius,
                   layout_min[1] - plate_margin + corner_radius])
            square([layout_max[0] - layout_min[0] + 2*(plate_margin - corner_radius),
                    layout_max[1] - layout_min[1] + 2*(plate_margin - corner_radius)]);
        circle(r = corner_radius);
    }}
}}

module plate_cutouts_2d() {{
    pocket_xy = choc_body_xy + pocket_clearance;
    for (c = converters)
        translate([c[0], c[1]])
            rotate([0, 0, c[2]])
                square([pocket_xy, pocket_xy], center = true);
    for (k = normal_keys)
        translate([k[0], k[1]])
            rotate([0, 0, k[2]])
                square([switch_cutout, switch_cutout], center = true);
}}

module integrated_plate() {{
    union() {{
        translate([0, 0, body_h - plate_t])
            linear_extrude(plate_t)
                difference() {{
                    plate_outline_2d();
                    plate_cutouts_2d();
                }}
        placed_adapters(with_pins = true);
    }}
}}

// ==========================================================================

if (part == "adapter")     adapter();
else if (part == "plate")  integrated_plate();
else                       panel();
"""