"""
Markdown documentation generator.

Produces a per-keyboard build document containing:
  * summary stats (keys, matrix, physical size)
  * wiring matrix table (row/col -> key label)
  * stabilizer list
  * bill of materials (switches, diodes, stabs, controller)
  * how-to-build instructions for every artifact the pipeline emitted
"""

from __future__ import annotations

from datetime import date
from typing import Dict, List

from ..layout import Layout


def generate_docs(layout: Layout, outputs: Dict[str, str] | None = None) -> str:
    """
    Generate Markdown documentation for the layout.

    Args:
        layout:  parsed Layout (matrix will be assigned if needed)
        outputs: optional mapping of artifact kind -> filename actually
                 written (e.g. {'ergogen': 'board.ergogen.yaml'}) used in
                 the build-instructions section.
    """
    layout.assign_matrix()
    stats = layout.stats()
    outputs = outputs or {}

    parts: List[str] = []
    parts.append(f"# {layout.name}")
    parts.append("")
    if layout.author:
        parts.append(f"*Author: {layout.author}*")
        parts.append("")
    if layout.notes:
        parts.append(layout.notes)
        parts.append("")
    parts.append(f"Generated by **kbforge** on {date.today().isoformat()}.")
    parts.append("")

    # ------------------------------------------------------------------ #
    parts.append("## Summary")
    parts.append("")
    parts.append("| Property | Value |")
    parts.append("|---|---|")
    parts.append(f"| Total keys | {stats['total_keys']} |")
    parts.append(f"| Switches | {stats['switch_count']} |")
    parts.append(f"| Stabilized keys (≥2u) | {stats['stabilized_keys']} |")
    parts.append(f"| Electrical matrix | {stats['matrix_rows']} rows × {stats['matrix_cols']} cols |")
    parts.append(f"| Physical size | {stats['size_mm'][0]} × {stats['size_mm'][1]} mm |")
    parts.append(f"| Key unit | {stats['unit_mm']} mm |")
    parts.append(f"| Rotated keys | {'yes' if stats['has_rotation'] else 'no'} |")
    widths = ", ".join(f"{w}u" for w in stats["unique_widths_u"])
    parts.append(f"| Key widths | {widths} |")
    parts.append("")

    # ------------------------------------------------------------------ #
    parts.append("## Wiring matrix")
    parts.append("")
    parts.append("Position-derived matrix (rows grouped by physical Y within 0.1u,")
    parts.append("columns ordered by X within each row). Use this as the starting")
    parts.append("point for firmware matrix definitions.")
    parts.append("")

    rows, cols = stats["matrix_rows"], stats["matrix_cols"]
    grid = [["" for _ in range(cols)] for _ in range(rows)]
    for key in layout.switches:
        label = key.primary_label or "·"
        label = label.replace("|", "\\|").replace("\n", " ")
        grid[key.matrix_row][key.matrix_col] = label

    header = "| | " + " | ".join(f"c{c}" for c in range(cols)) + " |"
    sep = "|---" * (cols + 1) + "|"
    parts.append(header)
    parts.append(sep)
    for r in range(rows):
        parts.append(f"| **r{r}** | " + " | ".join(grid[r][c] or " " for c in range(cols)) + " |")
    parts.append("")

    # ------------------------------------------------------------------ #
    if layout.stabilized:
        parts.append("## Stabilizers")
        parts.append("")
        parts.append("| Key | Size | Type | Stem spacing (mm) |")
        parts.append("|---|---|---|---|")
        for key in layout.stabilized:
            stab = key.stabilizer
            span = stab["left"] + stab["right"]
            orient = " (vertical)" if stab["vertical"] else ""
            parts.append(
                f"| {key.primary_label or f'r{key.matrix_row}c{key.matrix_col}'} "
                f"| {stab['size']}u{orient} | `{stab['type']}` | {span:.2f} |"
            )
        parts.append("")

    # ------------------------------------------------------------------ #
    parts.append("## Bill of materials")
    parts.append("")
    parts.append("| Item | Qty | Notes |")
    parts.append("|---|---|---|")
    parts.append(f"| MX-style switches | {stats['switch_count']} | hotswap sockets optional |")
    parts.append(f"| Diodes (1N4148) | {stats['switch_count']} | one per switch |")
    parts.append(f"| Keycaps | {stats['switch_count']} | sizes: {widths} |")
    if stats["stabilized_keys"]:
        parts.append(f"| Stabilizers | {stats['stabilized_keys']} | see table above |")
    parts.append("| Controller (e.g. Pro Micro) | 1 | wire per matrix table |")
    parts.append("")

    # ------------------------------------------------------------------ #
    parts.append("## Build pipeline")
    parts.append("")
    ergogen_file = outputs.get("ergogen", f"{_slug(layout.name)}.ergogen.yaml")
    scad_file = outputs.get("scad", f"{_slug(layout.name)}.scad")
    hotswap_file = outputs.get("hotswap", f"{_slug(layout.name)}.hotswap.scad")
    parts.append("### PCB, plates, cases and case STLs via Ergogen")
    parts.append(f"Review/edit `{ergogen_file}`, then run Ergogen on it")
    parts.append("(also renders the case STLs):")
    parts.append("```")
    parts.append(f"python -m kbforge {ergogen_file} -o <out>")
    parts.append("```")
    parts.append("* `ergogen/outlines/plate.dxf` — laser-cut/CNC switch plate")
    parts.append("* `ergogen/outlines/pcb_outline.dxf` — board edge")
    parts.append("* `ergogen/pcbs/*.kicad_pcb` — open in KiCad, route, fabricate")
    parts.append("* `ergogen/cases/*.jscad` — case_bottom / case_walls / case_plate 3D models")
    parts.append("* `ergogen/cases/*.stl` — the same case models, rendered printable")
    parts.append("")
    parts.append("Or manually:")
    parts.append("```")
    parts.append(f"npx ergogen {ergogen_file} -o output/")
    parts.append("npx --yes @jscad/cli@1 output/cases/case_bottom.jscad -o output/cases/case_bottom.stl")
    parts.append("```")
    parts.append("")
    parts.append("### 3D-printed plate & case via OpenSCAD (standalone)")
    parts.append("```")
    parts.append(f"openscad -o plate.stl  -D 'part=\"plate\"'  {scad_file}")
    parts.append(f"openscad -o bottom.stl -D 'part=\"bottom\"' {scad_file}")
    parts.append("```")
    parts.append("")
    parts.append("### Printable hotswap PCB via hotswap_pcb_generator")
    parts.append(f"Copy `{hotswap_file}` into the hotswap_pcb_generator `scad/` folder")
    parts.append("and set it as the layout include; render its pcb/plate/case parts.")
    parts.append("")

    return "\n".join(parts)


def _slug(text: str) -> str:
    import re
    return re.sub(r"[^A-Za-z0-9_-]+", "_", (text or "keyboard").strip()).strip("_").lower() or "keyboard"