"""
OpenSCAD generators.

Two outputs:

1. generate_scad(layout)
   A *standalone* parametric OpenSCAD model — no external libraries needed.
   Renders a switch plate (with 14x14mm MX cutouts and stabilizer slots) and
   a simple two-part case (bottom tray + walls). Open in OpenSCAD, pick the
   `part` to render, export STL. Supports rotated keys and any key size.

2. generate_hotswap_layout(layout)
   A data-only layout file for hotswap_pcb_generator
   (https://github.com/50an6xy06r6n/hotswap_pcb_generator) — the format the
   old kle-to-scad tool emitted. Drop it into that project's `scad/` folder
   as your layout to generate printable hotswap PCBs, plates, and cases.

All geometry math (positions, rotation, stabilizer offsets) comes from the
shared Layout model, so SCAD/Ergogen/docs outputs always agree.
"""

from __future__ import annotations

from typing import Any, Dict, List

from ..layout import Key, Layout

DEFAULTS = {
    "plate_thickness": 1.6,   # mm
    "plate_margin": 3.0,      # mm added around key footprint bounding area
    "switch_cutout": 14.0,    # mm, MX spec
    "corner_radius": 3.0,     # mm, plate/case corner rounding
    "wall": 3.0,              # mm, case wall thickness
    "bottom_thickness": 3.0,  # mm
    "case_height": 13.0,      # mm interior height (walls)
    "stab_slot_w": 7.0,       # mm, Cherry plate-mount stab slot width
    "stab_slot_h": 15.0,      # mm, slot height (generous, plate-mount)
}


# ---------------------------------------------------------------------- #
# 1. Standalone plate & case model
# ---------------------------------------------------------------------- #

def generate_scad(layout: Layout, options: Dict[str, Any] | None = None) -> str:
    """Generate a standalone OpenSCAD plate + case model for the layout."""
    opts = dict(DEFAULTS)
    if options:
        opts.update(options)

    layout.assign_matrix()
    unit = layout.unit
    bounds = layout.bounds_mm()

    # Key data table: [x_center, y_center, width_mm, height_mm, rotation_deg]
    # SCAD space: +y UP, so negate KLE y. Rotation: KLE cw -> SCAD ccw = negate.
    key_rows: List[str] = []
    for key in layout.switches:
        cx, cy = key.center_mm(unit)
        key_rows.append(
            f"  [{cx:.3f}, {-cy:.3f}, "
            f"{key.width * unit:.3f}, {key.height * unit:.3f}, "
            f"{-key.rotation_angle:.3f}]"
        )

    # Stabilizer stems: [x_center, y_center, rotation_deg, left_off, right_off, vertical]
    stab_rows: List[str] = []
    for key in layout.stabilized:
        stab = key.stabilizer
        cx, cy = key.center_mm(unit)
        stab_rows.append(
            f"  [{cx:.3f}, {-cy:.3f}, {-key.rotation_angle:.3f}, "
            f"{stab['left']:.3f}, {stab['right']:.3f}, "
            f"{'true' if stab['vertical'] else 'false'}]"
        )

    stats = layout.stats()

    return f"""// {layout.name} — generated by kbforge
// Switches: {stats['switch_count']}  |  Matrix: {stats['matrix_rows']}x{stats['matrix_cols']}  |  Size: {stats['size_mm'][0]} x {stats['size_mm'][1]} mm
//
// Standalone model: needs no external libraries.
// Set `part` below (or use the Customizer) and export STL:
//   "plate"  - switch plate with cutouts and stabilizer slots
//   "bottom" - case bottom tray (floor + walls)
//   "walls"  - wall ring only (for a sandwich/stacked case)
//   "all"    - assembled preview

/* [Part Selection] */
part = "all"; // [plate, bottom, walls, all]

/* [Dimensions] */
plate_thickness  = {opts['plate_thickness']};
plate_margin     = {opts['plate_margin']};
switch_cutout    = {opts['switch_cutout']};
corner_radius    = {opts['corner_radius']};
wall             = {opts['wall']};
bottom_thickness = {opts['bottom_thickness']};
case_height      = {opts['case_height']};
stab_slot_w      = {opts['stab_slot_w']};
stab_slot_h      = {opts['stab_slot_h']};

/* [Hidden] */
$fn = 32;

// Key data: [x_center, y_center, width_mm, height_mm, rotation_deg]
// (y is up; layout origin = KLE origin)
keys = [
{",\n".join(key_rows)}
];

// Stabilizers: [x_center, y_center, rotation_deg, left_offset, right_offset, vertical]
stabs = [
{",\n".join(stab_rows) if stab_rows else ""}
];

// Layout extents (mm, y-up space)
layout_min = [{bounds['min_x']:.3f}, {-bounds['max_y']:.3f}];
layout_max = [{bounds['max_x']:.3f}, {-bounds['min_y']:.3f}];

// ------------------------------------------------------------------ //
// 2D primitives
// ------------------------------------------------------------------ //

module rounded_plate_outline() {{
    // Rounded rectangle covering the whole layout plus margin.
    minkowski() {{
        translate([layout_min[0] - plate_margin + corner_radius,
                   layout_min[1] - plate_margin + corner_radius])
            square([layout_max[0] - layout_min[0] + 2*(plate_margin - corner_radius),
                    layout_max[1] - layout_min[1] + 2*(plate_margin - corner_radius)]);
        circle(r = corner_radius);
    }}
}}

module switch_cutouts_2d() {{
    for (k = keys)
        translate([k[0], k[1]])
            rotate([0, 0, k[4]])
                square([switch_cutout, switch_cutout], center = true);
}}

module stab_cutouts_2d() {{
    for (s = stabs)
        translate([s[0], s[1]])
            rotate([0, 0, s[2] + (s[5] ? 90 : 0)]) {{
                // Two stem slots at the Cherry spacing offsets
                translate([-s[3], 0]) square([stab_slot_w, stab_slot_h], center = true);
                translate([ s[4], 0]) square([stab_slot_w, stab_slot_h], center = true);
                // Connecting wire channel
                square([s[3] + s[4], 4.6], center = true);
            }}
}}

module plate_2d() {{
    difference() {{
        rounded_plate_outline();
        switch_cutouts_2d();
        stab_cutouts_2d();
    }}
}}

module case_outer_2d() {{
    // Plate outline grown by the wall thickness.
    minkowski() {{
        rounded_plate_outline();
        circle(r = wall);
    }}
}}

// ------------------------------------------------------------------ //
// 3D parts
// ------------------------------------------------------------------ //

module plate() {{
    linear_extrude(plate_thickness) plate_2d();
}}

module walls() {{
    linear_extrude(case_height)
        difference() {{
            case_outer_2d();
            rounded_plate_outline();
        }}
}}

module bottom() {{
    // Floor
    linear_extrude(bottom_thickness) case_outer_2d();
    // Walls on top of the floor
    translate([0, 0, bottom_thickness]) walls();
}}

module assembled() {{
    color("SteelBlue") bottom();
    color("Silver")
        translate([0, 0, bottom_thickness + case_height])
            plate();
}}

// ------------------------------------------------------------------ //

if (part == "plate")       plate();
else if (part == "bottom") bottom();
else if (part == "walls")  walls();
else                       assembled();
"""


# ---------------------------------------------------------------------- #
# 2. hotswap_pcb_generator layout file
# ---------------------------------------------------------------------- #

def generate_hotswap_layout(layout: Layout) -> str:
    """
    Generate a hotswap_pcb_generator-compatible layout .scad file.

    Format per key (from hotswap_pcb_generator):
        [ [[x, y], key_size, [rotation, rot_x, rot_y]],
          [top_border, bottom_border, left_border, right_border],
          extra_data ]

    Positions are the KLE top-left corner in key units; rotation is negated
    (KLE cw -> SCAD ccw); wide keys get symmetric extra side borders.
    """
    layout.assign_matrix()

    def key_entry(key: Key) -> str:
        side_border = (key.width - 1) / 2
        border = f"1+{side_border}*unit*mm" if side_border else "1"
        rot = -key.rotation_angle
        loc = (f"[[{_n(key.x)},{_n(key.y)}],{_n(key.width)},"
               f"[{_n(rot)},{_n(key.rotation_x)},{_n(key.rotation_y)}]]")
        return f"  [{loc},[1,1,{border},{border}],false]"

    def stab_entry(key: Key) -> str:
        side_border = (key.width - 1) / 2
        border = f"1+{side_border}*unit*mm" if side_border else "1"
        rot = -key.rotation_angle
        loc = (f"[[{_n(key.x)},{_n(key.y)}],{_n(key.width)},"
               f"[{_n(rot)},{_n(key.rotation_x)},{_n(key.rotation_y)}]]")
        return f"  [{loc},[1,1,{border},{border}],{key.stabilizer['type']}]"

    stats = layout.stats()

    switch_lines = ",\n".join(key_entry(k) for k in layout.switches)
    stab_lines = ",\n".join(stab_entry(k) for k in layout.stabilized)

    return f"""// Generated from KLE by kbforge
// Keys: {stats['switch_count']}
// Stabilized keys: {stats['stabilized_keys']}
// For use with hotswap_pcb_generator
// (requires its parameters.scad, stabilizer_spacing.scad, utils.scad)

include <parameters.scad>
include <stabilizer_spacing.scad>

use <utils.scad>

/* [Layout Values] */
/* Layout Format (each key):
    [
        [                                       // Location Data
            [x_location, y_location],
            key_size,
            [rotation, rotation_x, rotation_y],
        ],
        [                                       // Borders
            top_border,
            bottom_border,
            left_border,
            right_border
        ],
        extra_data                              // Extra data (depending on component type)
    ]
*/

// Keyswitch Layout
base_switch_layout = [
{switch_lines}
];

// MCU Position(s)
base_mcu_layout = [];

// TRRS Position(s)
base_trrs_layout = [];

// Stabilizer layout
//     (extra_data = stabilizer type constant from stabilizer_spacing.scad)
base_stab_layout = [
{stab_lines}
];

// Via layout
base_via_layout = [];

// Plate Layout
base_plate_layout = [];

// Standoff layout
base_standoff_layout = [];

module additional_plate_cutouts() {{
    square(0);
}}

module additional_case_cavities() {{
    square(0);
}}

// Configuration flags
use_plate_layout_only = false;
invert_layout_flag = false;
layout_type = "column";
tent_angle_y = 0;
tent_angle_x = 0;
tent_point = [0, 0, 0];
"""


def _n(value: float) -> str:
    """Compact numeric literal for SCAD output."""
    if value == int(value):
        return str(int(value))
    return f"{value:.4f}".rstrip("0").rstrip(".")