points:
  zones:
    matrix:
      anchor:
        rotate: 5
      columns:
        pinky:
          rows:
            home:
              bind: [,15,-1]
            top:
              bind: [,15,-1]
          key:
            column_net: P4
            column_mark: P
        ring:
          rotate: -5
          origin: [-12, -19]
          stagger: 12
          rows:
            bottom:
              bind: [,,,10]
            home:
              bind: [,10]
            top:
              bind: [,10]
          key:
            column_net: P5
            column_mark: R
        middle:
          stagger: 5
          rows:
            bottom:
              bind: [,10,,10]
            home:
              bind: [,10,,10]
          key:
            column_net: P7
            column_mark: M
        index:
          stagger: -6
          rows:
            bottom:
              bind: [,10]
            home:
              bind: [,,,10]
            top:
              bind: [,,,10]
          key:
            column_net: P8
            column_mark: X
        inner:
          stagger: -2
          rows:
            bottom:
              bind: [,,10,]
            home:
              bind: [,,,10]
            top:
              bind: [,,,10]
          key:
            column_net: P1
            column_mark: I
      rows:
        bottom:
          bind: [10]
          row_net: P16
          row_mark: LB
          mirror:
            row_net: P9
            row_mark: RB
        home:
          bind: [10]
          row_net: P15
          row_mark: LH
          mirror:
            row_net: P6
            row_mark: RH
        top:
          row_net: P20
          row_mark: LT
          mirror:
            row_net: P2
            row_mark: RT
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -19]
      columns:
        near:
          rows:
            thumb:
              bind: [10,5,,]
              column_net: P7
        home:
          spread: 21.25
          rotate: -28
          origin: [-11.75, -9]
          rows:
            thumb:
              bind: [,10,,15]
              column_net: P8
        far:
          spread: 21.25
          rotate: -28
          origin: [-9.5, -9]
          rows:
            thumb:
              bind: [-1,,,5]
              column_net: P1
      rows:
        thumb:
          row_net: P10
          row_mark: LF
          mirror:
            row_net: P19
            row_mark: RF
  key:
    bind: [0,0,0,0]
  rotate: -20
  mirror:
    ref: matrix_pinky_home
    distance: 223.7529778
outlines:
  glue:
    classic_s19:
      top:
        left:
          ref: matrix_inner_top
          shift: [, 0.5 sy]
        right:
          ref: mirror_matrix_inner_top
          shift: [, 0.5 sy]
      bottom:
        left:
          ref: thumbfan_far_thumb
          shift: [0.5 sx, 0]
          rotate: 90
        right:
          ref: mirror_thumbfan_far_thumb
          shift: [0.5 sx, 0]
          rotate: 90
      waypoints:
        - percent: 50
          width: 50
        - percent: 90
          width: 25
  exports:
    classic_s19_pcb:
      main:
        type: keys
        side: both
        tags:
          - s19
          - classic
        glue: classic_s19
        size: 13.5
        corner: .5
pcbs:
  main:
    outlines:
      edge:
        outline: intersected_outline
        layer: Edge.Cuts
    footprints:
      mcu:
        type: promicro
        anchor:
          ref:
            - s18_inner_top
            - mirror_s18_inner_top
          shift: [0, -23]
          rotate: 270
