#!/bin/bash

echo "🔍 Creating Self-Contained DXF Viewer VSIX"
echo "=========================================="

# Clean up any existing build
rm -rf extension-self-contained/
rm -f ergogen-dxf-viewer-self-contained-*.vsix

echo "📁 Copying self-contained extension files..."
mkdir -p extension-self-contained/extension

# Copy the main extension file
cp self-contained-extension.js extension-self-contained/extension/
cp package-self-contained.json extension-self-contained/extension/package.json

# Create README
cat > extension-self-contained/extension/README.md << 'EOF'
# Ergogen DXF Viewer (Self-Contained)

A self-contained VSCode extension for viewing DXF files generated by Ergogen.

## Features

- ✅ **Zero setup** - no external servers or dependencies
- ✅ **Dark mode** - matches VSCode theme
- ✅ **File watching** - automatically updates when DXF files change
- ✅ **Interactive viewer** - pan, zoom, and navigate DXF drawings
- ✅ **Integrated workflow** - run Ergogen with Ctrl+Shift+E

## Usage

1. Open a YAML file in your Ergogen project
2. Press Ctrl+Shift+P and run "Ergogen: Open DXF Viewer"
3. Press Ctrl+Shift+E to run Ergogen and generate DXF files
4. View the generated DXF files in the integrated viewer

## Commands

- `Ergogen: Open DXF Viewer` - Open the DXF viewer panel
- `Ergogen: Run Ergogen` - Run Ergogen on the current YAML file
- `Ergogen: Test Extension` - Test that the extension is working

## Keyboard Shortcuts

- `Ctrl+Shift+E` - Run Ergogen (when a YAML file is active)
EOF

echo "📝 Creating VSIX manifest..."
cat > extension-self-contained/[Content_Types].xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="json" ContentType="application/json"/>
  <Default Extension="js" ContentType="application/javascript"/>
  <Default Extension="md" ContentType="text/markdown"/>
</Types>
EOF

mkdir -p extension-self-contained/META-INF
cat > extension-self-contained/META-INF/MANIFEST.MF << 'EOF'
Manifest-Version: 1.0

EOF

echo "🗜️  Creating self-contained VSIX archive..."
cd extension-self-contained
zip -r ../ergogen-dxf-viewer-self-contained-1.0.0.vsix . -x "*.DS_Store"
cd ..

echo "✅ Self-contained VSIX created: ergogen-dxf-viewer-self-contained-1.0.0.vsix"
echo ""
echo "🚀 To install and test:"
echo "  1. Uninstall any previous versions"
echo "  2. Install: ergogen-dxf-viewer-self-contained-1.0.0.vsix"
echo "  3. Restart VSCode"
echo "  4. Test: Ergogen: Open DXF Viewer"
echo "  5. Test: Ergogen: Run Ergogen"
echo ""
echo "🎯 This version features:"
echo "  • Self-contained - no external servers needed"
echo "  • Built-in DXF parsing in JavaScript"
echo "  • VSCode native file watching"
echo "  • Dark mode interface"
echo "  • Zero configuration required"