// Numpad Example — switch-converter panel / integrated plate
// Generated by kbforge (converter format).
// Converter positions: 17 of 17 switches.
//
// Adapter geometry inlined from
// projects/switch_converter/OpenSCAD/pg1350_to_pg1425_adapter.scad (v3.1):
// a 15x15x5mm carrier that seats a Kailh Choc PG1350 switch onto a Kailh
// PG1425 "Choc X" PCB footprint. The top 1.2mm of its bezel walls act as
// the switch plate (clip windows included). v3.1: routing slots are now
// CAPTIVE WIRE CHANNELS (0.5mm bottom membrane, open top, through-openings
// only at the pin entry pockets and the wire exit holes).
//
// Parts:
//   "adapter" - one adapter at the origin
//   "panel"   - all adapters at board positions, joined by snap-off sprues
//   "plate"   - integrated converter plate (adapters fused into one plate)

/* [Part Selection] */
part = "panel"; // [adapter, panel, plate]

/* [Panel] */
sprue_w = 2.0;
sprue_h = 0.8;
sprue_inset = 7.0;   // sprue endpoints this far from adapter centers

/* [Plate] */
plate_margin  = 3.0;
corner_radius = 3.0;
switch_cutout = 14.0;   // cutout for non-converter keys

/* [Hidden] */
$fn = 48;

// Converter positions: [x_center, y_center, rotation_deg]  (y-up)
converters = [
  [9.525, -9.525, -0.000],
  [28.575, -9.525, -0.000],
  [47.625, -9.525, -0.000],
  [66.675, -9.525, -0.000],
  [9.525, -28.575, -0.000],
  [28.575, -28.575, -0.000],
  [47.625, -28.575, -0.000],
  [66.675, -38.100, -0.000],
  [9.525, -47.625, -0.000],
  [28.575, -47.625, -0.000],
  [47.625, -47.625, -0.000],
  [9.525, -66.675, -0.000],
  [28.575, -66.675, -0.000],
  [47.625, -66.675, -0.000],
  [66.675, -76.200, -0.000],
  [19.050, -85.725, -0.000],
  [47.625, -85.725, -0.000]
];

// Non-converter switch positions: [x_center, y_center, rotation_deg]
normal_keys = [

];

// Sprue pairs: [x1, y1, x2, y2]
sprues = [
  [9.525, -9.525, 28.575, -9.525],
  [9.525, -9.525, 9.525, -28.575],
  [9.525, -9.525, 28.575, -28.575],
  [28.575, -9.525, 47.625, -9.525],
  [28.575, -9.525, 9.525, -28.575],
  [28.575, -9.525, 28.575, -28.575],
  [28.575, -9.525, 47.625, -28.575],
  [47.625, -9.525, 66.675, -9.525],
  [47.625, -9.525, 28.575, -28.575],
  [47.625, -9.525, 47.625, -28.575],
  [66.675, -9.525, 47.625, -28.575],
  [66.675, -9.525, 66.675, -38.100],
  [9.525, -28.575, 28.575, -28.575],
  [9.525, -28.575, 9.525, -47.625],
  [9.525, -28.575, 28.575, -47.625],
  [28.575, -28.575, 47.625, -28.575],
  [28.575, -28.575, 9.525, -47.625],
  [28.575, -28.575, 28.575, -47.625],
  [28.575, -28.575, 47.625, -47.625],
  [47.625, -28.575, 66.675, -38.100],
  [47.625, -28.575, 28.575, -47.625],
  [47.625, -28.575, 47.625, -47.625],
  [66.675, -38.100, 47.625, -47.625],
  [9.525, -47.625, 28.575, -47.625],
  [9.525, -47.625, 9.525, -66.675],
  [9.525, -47.625, 28.575, -66.675],
  [28.575, -47.625, 47.625, -47.625],
  [28.575, -47.625, 9.525, -66.675],
  [28.575, -47.625, 28.575, -66.675],
  [28.575, -47.625, 47.625, -66.675],
  [47.625, -47.625, 28.575, -66.675],
  [47.625, -47.625, 47.625, -66.675],
  [9.525, -66.675, 28.575, -66.675],
  [9.525, -66.675, 19.050, -85.725],
  [28.575, -66.675, 47.625, -66.675],
  [28.575, -66.675, 19.050, -85.725],
  [28.575, -66.675, 47.625, -85.725],
  [47.625, -66.675, 66.675, -76.200],
  [47.625, -66.675, 47.625, -85.725],
  [66.675, -76.200, 47.625, -85.725],
  [19.050, -85.725, 47.625, -85.725]
];

// Layout extents (mm, y-up space)
layout_min = [0.000, -95.250];
layout_max = [76.200, -0.000];

// ==========================================================================
// PG1350 -> PG1425 ADAPTER (inlined from pg1350_to_pg1425_adapter.scad v3.1)
// z = 0 is the adapter's bottom face (sits on the PG1425 PCB);
// alignment pins extend below z = 0.
// ==========================================================================

pocket_clearance = 0.30;
hole_clearance   = 0.20;
post_clearance   = 0.15;
eps              = 0.10;

choc_body_xy         = 13.80;
choc_body_h          = 2.20;
choc_flange_xy       = 15.00;
choc_center_post_d   = 3.20;
choc_center_post_len = 2.65;
choc_side_post_d     = 1.90;
choc_side_post_x     = 5.50;
choc_pin1_pos        = [ 0.0, 5.9 ];
choc_pin2_pos        = [ 5.0, 3.8 ];

pg1425_align_hole_d    = 1.30;
pg1425_align_positions = [ [ 5.5, -5.5], [-5.5,  5.5] ];
pg1425_align_pin_h     = 1.40;
pg1425_pin1_pos        = [-3.4,  2.9];
pg1425_pin2_pos        = [-3.4, -2.0];

body_x  = choc_flange_xy;
body_y  = choc_flange_xy;
wall_t  = (choc_flange_xy - choc_body_xy - pocket_clearance) / 2;
wall_h  = choc_body_h;
floor_h = choc_center_post_len + 0.15;
body_h  = floor_h + wall_h;
adapter_corner_radius = 0.5;

plate_t       = 1.20;
clip_window_w = 6.0;
slot_w        = 1.4;

// v3.1 captive wire channels
wire_channel       = true;   // true = captive channel; false = v3 through-slot
channel_membrane_t = 0.50;   // floor membrane under the channel
wire_exit_hole_d   = 1.40;   // through-hole over each PG1425 plated hole
pin_entry_pocket_d = 1.60;   // through-pocket at each Choc pin position

adapter_slots = [
    [ choc_pin1_pos, pg1425_pin1_pos ],
    [ choc_pin2_pos, [2.4, -3.0], pg1425_pin2_pos ],
];

module rounded_block(x, y, h, r) {
    if (r > 0) {
        linear_extrude(height = h)
            offset(r = r) offset(delta = -r)
                square([x, y], center = true);
    } else {
        translate([0, 0, h/2]) cube([x, y, h], center = true);
    }
}

module adapter_body() {
    rounded_block(body_x, body_y, body_h, adapter_corner_radius);
}

module choc_pocket() {
    pocket_xy = choc_body_xy + pocket_clearance;
    translate([0, 0, floor_h])
        rounded_block(pocket_xy, pocket_xy, wall_h + eps, 0.3);
}

module clip_windows() {
    window_h = wall_h - plate_t + eps;
    for (sy = [-1, 1])
        translate([0, sy * (body_y/2 - wall_t/2), floor_h + window_h/2 - eps/2])
            cube([clip_window_w, wall_t + 2*eps, window_h], center = true);
}

module through_hole(pos, d) {
    translate([pos[0], pos[1], -eps])
        cylinder(h = floor_h + 2*eps, d = d + hole_clearance);
}

module pg1350_holes() {
    through_hole([0, 0], choc_center_post_d);
    through_hole([-choc_side_post_x, 0], choc_side_post_d);
    through_hole([ choc_side_post_x, 0], choc_side_post_d);
}

module routing_slot(pts) {
    z0 = wire_channel ? channel_membrane_t : -eps;
    h  = wire_channel ? (floor_h - channel_membrane_t + eps) : (floor_h + 2*eps);
    translate([0, 0, z0])
        linear_extrude(height = h)
            for (i = [0 : len(pts) - 2])
                hull() {
                    translate(pts[i])     circle(d = slot_w);
                    translate(pts[i + 1]) circle(d = slot_w);
                }
}

module pin_routing_slots() {
    for (s = adapter_slots) routing_slot(s);
}

// v3.1: through-openings at the channel ends
module channel_end_openings() {
    for (p = [choc_pin1_pos, choc_pin2_pos])
        translate([p[0], p[1], -eps])
            cylinder(h = floor_h + 2*eps, d = pin_entry_pocket_d);
    for (p = [pg1425_pin1_pos, pg1425_pin2_pos])
        translate([p[0], p[1], -eps])
            cylinder(h = floor_h + 2*eps, d = wire_exit_hole_d);
}

module pg1425_alignment_pins() {
    for (p = pg1425_align_positions)
        translate([p[0], p[1], -pg1425_align_pin_h])
            cylinder(h = pg1425_align_pin_h + eps,
                     d = pg1425_align_hole_d - post_clearance);
}

module adapter(with_pins = true) {
    union() {
        difference() {
            adapter_body();
            choc_pocket();
            clip_windows();
            pg1350_holes();
            pin_routing_slots();
            if (wire_channel) channel_end_openings();
        }
        if (with_pins) pg1425_alignment_pins();
    }
}

// ==========================================================================
// PANEL (Variant A): adapters at true board positions + snap-off sprues
// ==========================================================================

module placed_adapters(with_pins = true) {
    for (c = converters)
        translate([c[0], c[1], 0])
            rotate([0, 0, c[2]])
                adapter(with_pins);
}

module sprue_bars() {
    // Thin bars spanning the gaps between neighboring adapter bodies,
    // overlapping ~0.5mm into each solid floor for adhesion. Snap or cut
    // them off after printing.
    linear_extrude(height = sprue_h)
        for (s = sprues) {
            dx = s[2] - s[0];
            dy = s[3] - s[1];
            d  = norm([dx, dy]);
            ux = dx / d;
            uy = dy / d;
            hull() {
                translate([s[0] + ux*sprue_inset, s[1] + uy*sprue_inset])
                    circle(d = sprue_w);
                translate([s[2] - ux*sprue_inset, s[3] - uy*sprue_inset])
                    circle(d = sprue_w);
            }
        }
}

module panel() {
    placed_adapters(with_pins = true);
    sprue_bars();
}

// ==========================================================================
// INTEGRATED PLATE (Variant B): plate slab fused with the adapters
//
// Slab spans z = body_h - plate_t .. body_h, so its top is flush with the
// adapter tops and the Choc flanges rest on it. At converter positions the
// slab opens to the adapter pocket (the bezel walls merge seamlessly with
// the slab); the clip windows sit BELOW the slab, so they stay functional.
// Non-converter keys get standard switch cutouts (note: the slab sits at
// the converter-stack height — mixing in normal plate-mount switches only
// makes sense if their PCB is raised to match).
// ==========================================================================

module plate_outline_2d() {
    minkowski() {
        translate([layout_min[0] - plate_margin + corner_radius,
                   layout_min[1] - plate_margin + corner_radius])
            square([layout_max[0] - layout_min[0] + 2*(plate_margin - corner_radius),
                    layout_max[1] - layout_min[1] + 2*(plate_margin - corner_radius)]);
        circle(r = corner_radius);
    }
}

module plate_cutouts_2d() {
    pocket_xy = choc_body_xy + pocket_clearance;
    for (c = converters)
        translate([c[0], c[1]])
            rotate([0, 0, c[2]])
                square([pocket_xy, pocket_xy], center = true);
    for (k = normal_keys)
        translate([k[0], k[1]])
            rotate([0, 0, k[2]])
                square([switch_cutout, switch_cutout], center = true);
}

module integrated_plate() {
    union() {
        translate([0, 0, body_h - plate_t])
            linear_extrude(plate_t)
                difference() {
                    plate_outline_2d();
                    plate_cutouts_2d();
                }
        placed_adapters(with_pins = true);
    }
}

// ==========================================================================

if (part == "adapter")     adapter();
else if (part == "plate")  integrated_plate();
else                       panel();
