// le-oeuf - switch-converter panel / integrated plate
// Generated by generate_converter_scad.py from
//   D:\GitHub2\eggsworks\le-oeuf\le-oeuf\le-oeuf.kicad_pcb
// Converter positions: 36 of 36 switches
// (all keys use the Kailh-PG1425-X-Switch footprint).
//
// Adapter geometry inlined from
// projects/switch_converter/OpenSCAD/pg1350_to_pg1425_adapter.scad (v3.1):
// a 15x15x5mm carrier that seats a Kailh Choc PG1350 switch onto a Kailh
// PG1425 "Choc X" PCB footprint. The top 1.2mm of its bezel walls act as
// the switch plate (clip windows included).
//
// Parts:
//   "adapter" - one adapter at the origin
//   "panel"   - all adapters at board positions, joined by snap-off sprues
//   "plate"   - integrated converter plate (adapters fused into one plate
//               whose outline is the actual le-oeuf PCB Edge.Cuts)

/* [Part Selection] */
part = "plate"; // [adapter, panel, plate]

/* [Panel] */
sprue_w = 2.0;
sprue_h = 0.8;
sprue_inset = 7.0;   // sprue endpoints this far from adapter centers

/* [Plate] */
plate_pins        = false; // per-key alignment pins under the plate.
                           // false (default) = flat bottom, prints flat on
                           // the bed with ZERO supports; the plate outline
                           // matching the PCB edge provides alignment.
                           // true = pins included; print on a >=1.4mm raft
                           // or with supports.
plate_edge_offset = 0.0;   // grow (+) / shrink (-) the PCB outline, mm
clip_relief_depth = 1.2;   // slab relief behind each clip window, mm

// Center relief: thins the middle bridge (between the two key clusters)
// from BELOW, leaving center_top_t of material on top, so components
// mounted on the PCB under that section have clearance. The X span is
// auto-computed from the key clusters (adapter footprints stay full
// thickness); the top surface stays flush.
center_relief   = true;
center_top_t    = 1.5;     // remaining plate thickness over the relief, mm
center_relief_x = [123.295, 154.395];  // X span of the relief

mcu_cutout        = false; // full through-cutout, if partial relief isn't enough
mcu_cutout_center = [138.906, -53.465];
mcu_cutout_size   = [30, 40];

/* [Hidden] */
$fn = 48;

// Converter positions: [x_center, y_center, rotation_deg]  (y-up)
converters = [
  [46.506299, -59.758175, -7.0],   // SW1
  [63.939394, -57.611633, -7.0],   // SW2
  [81.330623, -55.465091, -7.0],   // SW3
  [97.685963, -61.755191, -7.0],   // SW4
  [114.437379, -63.819515, -7.0],   // SW5
  [163.253248, -63.826969, 7.0],   // SW6
  [180.248401, -61.747737, 7.0],   // SW7
  [196.481872, -55.465091, 7.0],   // SW8
  [213.873101, -57.611633, 7.0],   // SW9
  [231.264331, -59.758175, 7.0],   // SW10
  [44.476386, -76.631460, -7.0],   // SW11
  [61.867615, -74.484918, -7.0],   // SW12
  [79.258844, -72.338375, -7.0],   // SW13
  [95.614184, -78.628475, -7.0],   // SW14
  [112.487469, -80.700254, -7.0],   // SW15
  [165.325027, -80.700254, 7.0],   // SW16
  [182.198311, -78.628475, 7.0],   // SW17
  [198.553651, -72.338375, 7.0],   // SW18
  [215.944880, -74.484918, 7.0],   // SW19
  [233.336110, -76.631460, 7.0],   // SW20
  [42.404607, -93.504744, -7.0],   // SW21
  [59.795836, -91.358202, -7.0],   // SW22
  [77.187065, -89.211660, -7.0],   // SW23
  [93.542405, -95.501760, -7.0],   // SW24
  [110.415690, -97.573539, -7.0],   // SW25
  [167.518674, -97.566085, 7.0],   // SW26
  [184.270090, -95.501760, 7.0],   // SW27
  [200.625430, -89.211660, 7.0],   // SW28
  [218.016659, -91.358202, 7.0],   // SW29
  [235.407888, -93.504744, 7.0],   // SW30
  [74.707024, -110.409974, -7.0],   // SW31
  [91.470626, -112.375044, -7.0],   // SW32
  [108.343911, -114.446823, -7.0],   // SW33
  [169.468584, -114.446823, 7.0],   // SW34
  [186.341869, -112.375044, 7.0],   // SW35
  [203.215153, -110.303266, 7.0],   // SW36
];

// Sprue pairs: [x1, y1, x2, y2]
sprues = [
  [46.506, -59.758, 63.939, -57.612],
  [46.506, -59.758, 44.476, -76.631],
  [46.506, -59.758, 61.868, -74.485],
  [63.939, -57.612, 81.331, -55.465],
  [63.939, -57.612, 61.868, -74.485],
  [63.939, -57.612, 79.259, -72.338],
  [81.331, -55.465, 97.686, -61.755],
  [81.331, -55.465, 79.259, -72.338],
  [97.686, -61.755, 114.437, -63.820],
  [97.686, -61.755, 79.259, -72.338],
  [97.686, -61.755, 95.614, -78.628],
  [97.686, -61.755, 112.487, -80.700],
  [114.437, -63.820, 95.614, -78.628],
  [114.437, -63.820, 112.487, -80.700],
  [163.253, -63.827, 180.248, -61.748],
  [163.253, -63.827, 165.325, -80.700],
  [163.253, -63.827, 182.198, -78.628],
  [180.248, -61.748, 196.482, -55.465],
  [180.248, -61.748, 165.325, -80.700],
  [180.248, -61.748, 182.198, -78.628],
  [180.248, -61.748, 198.554, -72.338],
  [196.482, -55.465, 213.873, -57.612],
  [196.482, -55.465, 198.554, -72.338],
  [213.873, -57.612, 231.264, -59.758],
  [213.873, -57.612, 198.554, -72.338],
  [213.873, -57.612, 215.945, -74.485],
  [231.264, -59.758, 215.945, -74.485],
  [231.264, -59.758, 233.336, -76.631],
  [44.476, -76.631, 61.868, -74.485],
  [44.476, -76.631, 42.405, -93.505],
  [44.476, -76.631, 59.796, -91.358],
  [61.868, -74.485, 79.259, -72.338],
  [61.868, -74.485, 59.796, -91.358],
  [61.868, -74.485, 77.187, -89.212],
  [79.259, -72.338, 95.614, -78.628],
  [79.259, -72.338, 77.187, -89.212],
  [95.614, -78.628, 112.487, -80.700],
  [95.614, -78.628, 77.187, -89.212],
  [95.614, -78.628, 93.542, -95.502],
  [95.614, -78.628, 110.416, -97.574],
  [112.487, -80.700, 93.542, -95.502],
  [112.487, -80.700, 110.416, -97.574],
  [165.325, -80.700, 182.198, -78.628],
  [165.325, -80.700, 167.519, -97.566],
  [165.325, -80.700, 184.270, -95.502],
  [182.198, -78.628, 198.554, -72.338],
  [182.198, -78.628, 167.519, -97.566],
  [182.198, -78.628, 184.270, -95.502],
  [182.198, -78.628, 200.625, -89.212],
  [198.554, -72.338, 215.945, -74.485],
  [198.554, -72.338, 200.625, -89.212],
  [215.945, -74.485, 233.336, -76.631],
  [215.945, -74.485, 200.625, -89.212],
  [215.945, -74.485, 218.017, -91.358],
  [233.336, -76.631, 218.017, -91.358],
  [233.336, -76.631, 235.408, -93.505],
  [42.405, -93.505, 59.796, -91.358],
  [59.796, -91.358, 77.187, -89.212],
  [59.796, -91.358, 74.707, -110.410],
  [77.187, -89.212, 93.542, -95.502],
  [77.187, -89.212, 74.707, -110.410],
  [93.542, -95.502, 110.416, -97.574],
  [93.542, -95.502, 74.707, -110.410],
  [93.542, -95.502, 91.471, -112.375],
  [93.542, -95.502, 108.344, -114.447],
  [110.416, -97.574, 91.471, -112.375],
  [110.416, -97.574, 108.344, -114.447],
  [167.519, -97.566, 184.270, -95.502],
  [167.519, -97.566, 169.469, -114.447],
  [167.519, -97.566, 186.342, -112.375],
  [184.270, -95.502, 200.625, -89.212],
  [184.270, -95.502, 169.469, -114.447],
  [184.270, -95.502, 186.342, -112.375],
  [184.270, -95.502, 203.215, -110.303],
  [200.625, -89.212, 218.017, -91.358],
  [200.625, -89.212, 203.215, -110.303],
  [218.017, -91.358, 235.408, -93.505],
  [218.017, -91.358, 203.215, -110.303],
  [74.707, -110.410, 91.471, -112.375],
  [91.471, -112.375, 108.344, -114.447],
  [169.469, -114.447, 186.342, -112.375],
  [186.342, -112.375, 203.215, -110.303]
];

// le-oeuf PCB Edge.Cuts outline, y-up (35 pts)
board_edge = [
  [245.938, -102.532], [214.520, -118.926], [214.354, -118.994], [214.179, -119.032],
  [161.722, -125.473], [160.998, -125.278], [160.612, -124.635], [157.096, -102.121],
  [156.758, -101.516], [156.108, -101.275], [121.704, -101.275], [121.054, -101.516],
  [120.716, -102.121], [117.200, -124.636], [116.815, -125.280], [116.092, -125.475],
  [63.744, -119.139], [63.568, -119.101], [63.401, -119.032], [31.874, -102.532],
  [31.452, -102.111], [31.345, -101.525], [37.746, -49.389], [38.031, -48.804],
  [38.616, -48.518], [72.563, -44.328], [72.624, -44.323], [72.685, -44.321],
  [195.823, -44.321], [222.580, -46.467], [239.196, -48.518], [239.781, -48.804],
  [240.066, -49.389], [246.468, -101.524], [246.360, -102.111]
];

// Layout extents (adapter centers, mm, y-up space)
layout_min = [42.405, -114.447];
layout_max = [235.408, -55.465];

// ==========================================================================
// PG1350 -> PG1425 ADAPTER (inlined from pg1350_to_pg1425_adapter.scad v3.1)
// z = 0 is the adapter's bottom face (sits on the PG1425 PCB);
// alignment pins extend below z = 0.
// ==========================================================================

pocket_clearance = 0.30;
hole_clearance   = 0.20;
post_clearance   = 0.15;
eps              = 0.10;

choc_body_xy         = 13.80;
choc_body_h          = 2.20;
choc_flange_xy       = 15.00;
choc_center_post_d   = 3.20;
choc_center_post_len = 2.65;
choc_side_post_d     = 1.90;
choc_side_post_x     = 5.50;
choc_pin1_pos        = [ 0.0, 5.9 ];
choc_pin2_pos        = [ 5.0, 3.8 ];

pg1425_align_hole_d    = 1.30;
pg1425_align_positions = [ [ 5.5, -5.5], [-5.5,  5.5] ];
pg1425_align_pin_h     = 1.40;
pg1425_pin1_pos        = [-3.4,  2.9];
pg1425_pin2_pos        = [-3.4, -2.0];

body_x  = choc_flange_xy;
body_y  = choc_flange_xy;
wall_t  = (choc_flange_xy - choc_body_xy - pocket_clearance) / 2;
wall_h  = choc_body_h;
floor_h = choc_center_post_len + 0.15;
body_h  = floor_h + wall_h;
adapter_corner_radius = 0.5;

plate_t       = 1.20;
clip_window_w = 6.0;
slot_w        = 1.4;

// v3.1 captive wire channels
wire_channel       = true;   // true = captive channel; false = v3 through-slot
channel_membrane_t = 0.50;   // floor membrane under the channel
wire_exit_hole_d   = 1.40;   // through-hole over each PG1425 plated hole
pin_entry_pocket_d = 1.60;   // through-pocket at each Choc pin position

adapter_slots = [
    [ choc_pin1_pos, pg1425_pin1_pos ],
    [ choc_pin2_pos, [2.4, -3.0], pg1425_pin2_pos ],
];

module rounded_block(x, y, h, r) {
    if (r > 0) {
        linear_extrude(height = h)
            offset(r = r) offset(delta = -r)
                square([x, y], center = true);
    } else {
        translate([0, 0, h/2]) cube([x, y, h], center = true);
    }
}

module adapter_body() {
    rounded_block(body_x, body_y, body_h, adapter_corner_radius);
}

module choc_pocket() {
    pocket_xy = choc_body_xy + pocket_clearance;
    translate([0, 0, floor_h])
        rounded_block(pocket_xy, pocket_xy, wall_h + eps, 0.3);
}

module clip_windows() {
    window_h = wall_h - plate_t + eps;
    for (sy = [-1, 1])
        translate([0, sy * (body_y/2 - wall_t/2), floor_h + window_h/2 - eps/2])
            cube([clip_window_w, wall_t + 2*eps, window_h], center = true);
}

module through_hole(pos, d) {
    translate([pos[0], pos[1], -eps])
        cylinder(h = floor_h + 2*eps, d = d + hole_clearance);
}

module pg1350_holes() {
    through_hole([0, 0], choc_center_post_d);
    through_hole([-choc_side_post_x, 0], choc_side_post_d);
    through_hole([ choc_side_post_x, 0], choc_side_post_d);
}

module routing_slot(pts) {
    z0 = wire_channel ? channel_membrane_t : -eps;
    h  = wire_channel ? (floor_h - channel_membrane_t + eps) : (floor_h + 2*eps);
    translate([0, 0, z0])
        linear_extrude(height = h)
            for (i = [0 : len(pts) - 2])
                hull() {
                    translate(pts[i])     circle(d = slot_w);
                    translate(pts[i + 1]) circle(d = slot_w);
                }
}

module pin_routing_slots() {
    for (s = adapter_slots) routing_slot(s);
}

// v3.1: through-openings at the channel ends
module channel_end_openings() {
    for (p = [choc_pin1_pos, choc_pin2_pos])
        translate([p[0], p[1], -eps])
            cylinder(h = floor_h + 2*eps, d = pin_entry_pocket_d);
    for (p = [pg1425_pin1_pos, pg1425_pin2_pos])
        translate([p[0], p[1], -eps])
            cylinder(h = floor_h + 2*eps, d = wire_exit_hole_d);
}

module pg1425_alignment_pins() {
    for (p = pg1425_align_positions)
        translate([p[0], p[1], -pg1425_align_pin_h])
            cylinder(h = pg1425_align_pin_h + eps,
                     d = pg1425_align_hole_d - post_clearance);
}

module adapter(with_pins = true) {
    union() {
        difference() {
            adapter_body();
            choc_pocket();
            clip_windows();
            pg1350_holes();
            pin_routing_slots();
            if (wire_channel) channel_end_openings();
        }
        if (with_pins) pg1425_alignment_pins();
    }
}

// ==========================================================================
// PANEL (Variant A): adapters at true board positions + snap-off sprues
// ==========================================================================

module placed_adapters(with_pins = true) {
    for (c = converters)
        translate([c[0], c[1], 0])
            rotate([0, 0, c[2]])
                adapter(with_pins);
}

module sprue_bars() {
    // Thin bars spanning the gaps between neighboring adapter bodies,
    // overlapping ~0.5mm into each solid floor for adhesion. Snap or cut
    // them off after printing.
    linear_extrude(height = sprue_h)
        for (s = sprues) {
            dx = s[2] - s[0];
            dy = s[3] - s[1];
            d  = norm([dx, dy]);
            ux = dx / d;
            uy = dy / d;
            hull() {
                translate([s[0] + ux*sprue_inset, s[1] + uy*sprue_inset])
                    circle(d = sprue_w);
                translate([s[2] - ux*sprue_inset, s[3] - uy*sprue_inset])
                    circle(d = sprue_w);
            }
        }
}

module panel() {
    placed_adapters(with_pins = true);
    sprue_bars();
}

// ==========================================================================
// INTEGRATED PLATE (Variant B): full-thickness slab fused with the adapters
//
// The slab spans z = 0 .. body_h - the SAME thickness as the switch
// converters - so the plate is flush with the adapter tops AND rests on the
// PCB like the adapters do. At converter positions the slab opens to the
// full 15x15 adapter footprint and the adapter body (with its pocket, clip
// windows, holes and wire channels) is fused in. Clip-relief cuts behind
// each bezel clip window keep the Choc retention clips functional.
//
// The plate outline is the actual le-oeuf Edge.Cuts PCB outline (arcs
// sampled), grown/shrunk by plate_edge_offset.
//
// NOTE: the slab underside now sits ON the PCB (z = 0). Any top-side PCB
// component under the slab footprint (diodes, MCU, slide switch, battery)
// will collide - use mcu_cutout to relieve it.
// ==========================================================================

module plate_outline_2d() {
    offset(delta = plate_edge_offset)
        polygon(board_edge);
}

module plate_cutouts_2d() {
    // full adapter footprint (rounded to match adapter_corner_radius) so
    // the fused adapter supplies all geometry within it, corner-gap free
    for (c = converters)
        translate([c[0], c[1]])
            rotate([0, 0, c[2]])
                offset(r = adapter_corner_radius)
                    offset(delta = -adapter_corner_radius)
                        square([body_x, body_y], center = true);
    if (mcu_cutout)
        translate(mcu_cutout_center)
            square(mcu_cutout_size, center = true);
}

// Relief voids cut into the slab directly behind each adapter clip window,
// so the Choc clips can still flex outward and snap into the windows.
module plate_clip_reliefs() {
    window_h = wall_h - plate_t + eps;
    for (c = converters)
        translate([c[0], c[1], 0])
            rotate([0, 0, c[2]])
                for (sy = [-1, 1])
                    translate([0,
                               sy * (body_y/2 + clip_relief_depth/2 - eps),
                               floor_h + window_h/2 - eps/2])
                        cube([clip_window_w,
                              clip_relief_depth + 2*eps,
                              window_h], center = true);
}

// Center relief: removes material from BELOW across the middle bridge
// (X span center_relief_x, full Y extent), leaving center_top_t on top.
// The adapters are unioned back afterwards, so key positions - if any
// fell inside the span - would remain full thickness.
module center_relief_cut() {
    span = center_relief_x[1] - center_relief_x[0];
    translate([center_relief_x[0], layout_min[1] - 200, -eps])
        cube([span, (layout_max[1] - layout_min[1]) + 400,
              body_h - center_top_t + eps]);
}

module integrated_plate() {
    union() {
        difference() {
            linear_extrude(body_h)
                difference() {
                    plate_outline_2d();
                    plate_cutouts_2d();
                }
            plate_clip_reliefs();
            if (center_relief) center_relief_cut();
        }
        placed_adapters(with_pins = plate_pins);
    }
}

// ==========================================================================

if (part == "adapter")     adapter();
else if (part == "plate")  integrated_plate();
else                       panel();
