units:
  hx: 21.5
  hy: 18.62
  mx: 2
  my: 1.1547mx
  dx: 3
  dy: 1.1547dx
  kx: 0.54/2
  ky: 1.1547kx
  fk: 3
  rx: kx
  ry: 1.1547rx
  wc: 15.2
  mcu_top: hy/3+2my
  gap: 1

points:
  zones:
    f:
      anchor:
        shift: [254-9hx/2-dx/2, -127+3hy]
      columns:
        c0:
          rows:
            r0: $unset
            r1: $unset
            r2: $unset
            r3:
              shift: [0]
        c1:
          rows:
            r0: $unset
          key:
            stagger: -2hy
            spread: 0
        c2:
          rows:
            r0: $unset
        c3:
          rows:
            r1:
              shift: [hx/2]
          key:
            stagger: -hy
            spread: hx/2
        c4:
          rows:
            r0: $unset
        c5:
          rows:
            r0: $unset
            r1: $unset
            r2:
              shift: [0]
      rows:
        r0:
        r1:
        r2:
          shift: [hx/2]
        r3:
          shift: [hx/2]
    t:
      anchor:
        shift: [254-5hx/2-dx/2, -127-hy-dy]
      columns:
        c1:
        c2:
        c3:
          rows:
            r1:
            r2:
              shift: [hx/2]
          key:
            stagger: -hy
            spread: hx/2
      rows:
        r1:
    top:
      anchor:
        ref: f_c1_r3
      columns:
        c1:
          key:
            column_net: C1
            mirror.column_net: M_C1
        c2:
          key:
            column_net: C2
            mirror.column_net: M_C2
        c3:
          key:
            column_net: C3
            mirror.column_net: M_C3
        c4:
          key:
            spread: hx/2
            stagger: -hy
            column_net: C4
            mirror.column_net: M_C4
        c5:
          key:
            spread: hx/2
            stagger: -hy
            column_net: C5
            mirror.column_net: M_C5
      rows:
        r3:
          row_net: R3
          rotate: -60
  key:
    spread: hx
    padding: hy
  mirror:
    ref: top_c5_r3
    distance: hx+dx

outlines:
  _main:
    - what: polygon
      points:
        - ref: thumb_c3_rt
          shift: [0, -2hy/3-my]
        - ref: thumb_c3_rt
          shift: [-2hx-mx, 2hy/3-my/2]
        - ref: thumb_c1_rt
          shift: [-hx/2-mx, -7hy/3-my/2]
        - ref: thumb_c1_rt
          shift: [hx/2, hy+my]
        - ref: thumb_c1_rt
          shift: [9hx/2+dx/2, my-dy/4-hy/3]
        - ref: mirror_thumb_c1_rt
          shift: [hx/2, hy+my]
        - ref: mirror_thumb_c3_rt
          shift: [-2hx-mx, 2hy/3-my/2]
        - ref: mirror_thumb_c3_rt
          shift: [0, -2hy/3-my]
        - ref: thumb_c3_rt
          shift: [hx+dx/2, -my+dy/4]

pcbs:
  mantis_reversible_split:
    outlines:
      main:
        outline: main_split
    footprints:
      keys:
        what: choc
        where: [top_c1_r3, top_c2_r3, top_c3_r3,
                home_c1_r2, home_c2_r2, home_c3_r2,
                bottom_c1_r1, bottom_c2_r1, bottom_c3_r1,
                thumb_c1_rt, thumb_c2_rt, thumb_c3_rt]
        adjust:
          rotate: 180
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          keycaps: false
          hotswap: false
          reverse: true
