meta:
  engine: 4.0.4
  name: keyboard_numpad
  version: 0.1
  author: cline

units:
  # Key measurements for MX switches
  kx: 19.05 # Key spacing horizontal (center-to-center) - standard MX spacing
  ky: 19.05 # Key spacing vertical (center-to-center) - standard MX spacing
  capx: 18 # MX Keycap width
  capy: 18 # MX Keycap height

  # Distances
  main_to_nav: 1.25*kx # Distance from numpad grid to nav column
  main_to_mcu: 1.5*ky # Distance from numpad grid to MCU
  main_to_screen: 1.5*ky # Distance from numpad grid to MCU

points:
  zones:
    # Numpad layout
    numpad:
      anchor.shift: [kx*3, ky*2] # Center the numpad on the PCB
      key:
        width: capx
        height: capy
        padding: ky
        spread: kx
        tags: [key, numpad_key]
      columns:
        # Num Lock, 7, 4, 1, 0
        col0:
          key:
            column_net: col0
            bind: [0,0,0,ky]
          rows:
            row0: # Num Lock
              tags: [key, numpad_key]
            row1: # 7
              tags: [key, numpad_key]
            row2: # 4
              tags: [key, numpad_key]
            row3: # 1
              tags: [key, numpad_key]
            row4: # 0 (2u wide)
              width: 2*capx + kx
              tags: [key, numpad_key, zero_key]
        # /, 8, 5, 2
        col1:
          key:
            column_net: col1
          rows:
            row0: # /
              tags: [key, numpad_key]
            row1: # 8
              tags: [key, numpad_key]
            row2: # 5
              tags: [key, numpad_key]
            row3: # 2
              tags: [key, numpad_key]
            # No row4 for col1
        # *, 9, 6, 3, .
        col2:
          key:
            column_net: col2
          rows:
            row0: # *
              tags: [key, numpad_key]
            row1: # 9
              tags: [key, numpad_key]
            row2: # 6
              tags: [key, numpad_key]
            row3: # 3
              tags: [key, numpad_key]
            row4: # .
              tags: [key, numpad_key]
        # -, +, Enter
        col3:
          key:
            column_net: col3
            #bind: [0,2.8ky,0,0]
          rows:
            row0: # -
              tags: [key, numpad_key]
            row1: # + (2u tall, spans row1-row2)
              height: 2*capy + ky
              tags: [key, numpad_key, plus_key]
            # No row2 for col3 (covered by 2u tall + key)
            row3: # Enter (2u tall, spans row3-row4)
              height: 2*capy + ky
              tags: [key, numpad_key, enter_key]
            # No row4 for col3 (covered by 2u tall Enter key)

      rows:
        # Num Lock, /, *, -
        row0:
          row_net: row0
        # 7, 8, 9, +
        row1:
          row_net: row1
        # 4, 5, 6, +
        row2:
          row_net: row2
        # 1, 2, 3, Enter
        row3:
          row_net: row3
        # 0, ., Enter
        row4:
          row_net: row4

    # Left navigation column
    nav:
      anchor:
        ref: numpad_col0_row0
        shift: [-main_to_nav, 0] # Position left of main grid
      key:
        width: capx
        height: capy
        padding: ky
        spread: kx
        tags: [key, nav_key]

      columns:
        nav_col:
          key:
            column_net: col_left
            tags: [key, nav_key]
      rows:
        row0:
          row_net: row0
          tags: [key, nav_key]
        row1:
          row_net: row1
          tags: [key, nav_key]
        row2:
          row_net: row2
          tags: [key, nav_key]
        row3:
          row_net: row3
          tags: [key, nav_key]
        row4:
          row_net: row4
          tags: [key, nav_key]

    # OLED screen - positioned at the top of right section
    oled_screen:
      anchor:
        ref: numpad_col3_row4
        shift: [main_to_screen + ky/2, 0] # Position at the top of the right section
      key:
        width: 32 # OLED width - slightly wider
        height: 16 # OLED height - slightly taller
        tags: [oled_screen]

    # Right side encoder - positioned below OLED
    encoder_left:
      anchor:
        ref: oled_screen
        shift: [main_to_screen/2, -ky-4] # Position below the OLED
      key:
        width: capx
        height: capy # Make it slightly taller
        tags: [key, encoder_key]
        column_net: col_enc_left
        row_net: row_enc_left

    # Bottom right encoder
    encoder_right:
      anchor:
        ref: oled_screen
        shift: [-main_to_screen/2, -ky-4] # Position to the right of main grid
      key:
        width: capx
        height: capy
        tags: [key, encoder_key]
        column_net: col_enc_right
        row_net: row_enc_right

    # Bottom center encoder - positioned below the other two encoders
    encoder_bottom:
      anchor:
        ref: oled_screen
        shift: [0, -3ky+7] # Position centered below the other two encoders
      key:
        width: capx
        height: capy
        tags: [key, encoder_key]
        column_net: col_enc_bottom
        row_net: row_enc_bottom

    # Thumb key - 1.5U centered below the bottom encoder
    thumb_bottom:
      anchor:
        ref: encoder_bottom
        shift: [0, -1.3ky] # Position further below the bottom encoder
      key:
        width: 1.5*capx # 1.5U width
        height: capy
        tags: [key, thumb_key]
        column_net: col_thumb
        row_net: row_thumb

    # MCU section
    mcu:
      anchor:
        ref: numpad_col2_row4
        shift: [0, main_to_mcu] # Position below main main
      key:
        width: 18 # Pro Micro width
        height: 33 # Pro Micro height
        tags: [mcu]

outlines:
  _numpad_outline:
    - what: rectangle
      where: [numpad_key] # Only regular 1U numpad keys
      bound: true # Use binding system for connected outline
      size: [U, U] # Standard key size

  _zero_key_outline:
    - what: rectangle
      bound: true
      size: [2*capx + kx, capy]
      where: [zero_key]

  _plus_key_outline:
    - what: rectangle
      bound: true
      size: [capx, 2*capy + ky]
      where: [plus_key]

  _enter_key_outline:
    - what: rectangle
      bound: true
      size: [capx, 2*capy + ky]
      where: [enter_key]

  _nav_column_outline:
    - what: rectangle
      bound: true
      size: [capx, capy]
      where: [nav_key]

  _encoder_outline:
    - what: rectangle
      bound: true
      where: [encoder_key]
      size: [capx, capy]

  _thumb_outline:
    - what: rectangle
      bound: true
      where: [thumb_key]
      size: [1.5*capx, capy] # Match the 1.5U width

  _mcu_outline:
    - what: rectangle
      where: [mcu]
      size: [18, 33]

  _oled_outline:
    - what: rectangle
      where: [oled_screen]
      size: [32, 16] # Match the increased size

  _complete_outline:
    - what: outline
      name: _numpad_outline
    - what: outline
      name: _zero_key_outline
      operation: stack
    - what: outline
      name: _plus_key_outline
      operation: stack
    - what: outline
      name: _enter_key_outline
      operation: stack
    - what: outline
      name: _nav_column_outline
      operation: stack
    - what: outline
      name: _encoder_outline
      operation: stack
    - what: outline
      name: _thumb_outline
      operation: stack
    - what: outline
      name: _oled_outline
      operation: stack

  _regular_numpad_cutout:
    - what: rectangle
      size: [14, 14] # Standard switch cutout size for regular numpad keys
      where: [numpad_key]

  _nav_cutout:
    - what: rectangle
      size: [14, 14] # Standard switch cutout size for nav keys
      where: [nav_key]

  _thumb_cutout:
    - what: rectangle
      size: [14, 14] # Standard switch cutout size for thumb key
      where: [thumb_key]

  _zero_key_cutout:
    - what: rectangle
      size: [14, 14] # Standard switch cutout but centered in 2u key
      where: [zero_key]

  _plus_key_cutout:
    - what: rectangle
      size: [14, 14] # Standard switch cutout but centered in 2u tall key
      where: [plus_key]

  _enter_key_cutout:
    - what: rectangle
      size: [14, 14] # Standard switch cutout but centered in 2u tall key
      where: [enter_key]

  _encoder_cutout:
    - what: circle
      radius: 3.5 # Standard EC11 encoder shaft cutout
      where: [encoder_key]

  _screen_cutout:
    - what: rectangle
      size: [28, 15] # Slightly larger OLED screen cutout
      where: [oled_screen]

  _mount_hole_cutout:
    - what: circle
      radius: 2.2 # Standard mounting hole
      where: [mount_hole]

  _switch_holes:
    - what: rectangle
      where: -component # All key positions
      size: 14 # 14x14mm square for MX switch cutout
      bound: false # Don't include in binding calculations

  _switch_clips:
    - what: rectangle
      where: -component # All key positions
      size: [5, 16] # 5x16mm clips for switch retention
      bound: false

  enter_key:
    - what: outline
      name: _enter_key_outline
  nav:
    - what: outline
      name: _nav_column_outline

  just_numpad:
    - what: outline
      name: _numpad_outline
    - what: outline
      name: _regular_numpad_cutout
      operation: subtract
    - what: outline
      name: _enter_key_outline
      operation: stack

  numpad:
    - what: outline
      name: _numpad_outline
    - what: outline
      name: _zero_key_outline
      operation: add
    - what: outline
      name: _plus_key_outline
      operation: add
    - what: outline
      name: _enter_key_outline
      operation: add
    - what: outline
      name: _regular_numpad_cutout
      operation: subtract
    - what: outline
      name: _zero_key_cutout
      operation: subtract
    - what: outline
      name: _plus_key_cutout
      operation: subtract
    - what: outline
      name: _enter_key_cutout
      operation: subtract

  plate:
    - what: rectangle
      where: true # All key positions
      bound: true # Use binding system for connected outline
      size: 1U # 19x19mm base size
      corner: .5 # 0.5mm corner radius
    - what: outline
      name: _switch_holes # Remove switch cutouts
      operation: subtract

  switchplate:
    - what: outline
      name: plate
    - what: outline
      name: _regular_numpad_cutout
      operation: subtract
    - what: outline
      name: _nav_cutout
      operation: subtract
    - what: outline
      name: _thumb_cutout
      operation: subtract
    - what: outline
      name: _zero_key_cutout
      operation: subtract
    - what: outline
      name: _plus_key_cutout
      operation: subtract
    - what: outline
      name: _enter_key_cutout
      operation: subtract
    - what: outline
      name: _encoder_cutout
      operation: subtract
    - what: outline
      name: _screen_cutout
      operation: subtract

  pcb_outline:
    - what: outline
      name: _complete_outline
      fillet: 3
      expand: 2 # Expansion for PCB
    - what: outline
      name: _mount_hole_cutout
      operation: subtract

  case_outline:
    - what: outline
      name: _complete_outline
      fillet: 3
      expand: 5 # 5mm walls around the PCB
    - what: outline
      name: _mount_hole_cutout
      operation: subtract

pcbs:
  keyboard_numpad:
    outlines:
      main:
        outline: pcb_outline
    footprints:
      mx_switches:
        what: mx
        where: [numpad_key, nav_key]
        params:
          hotswap: true
          reverse: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      # Special numpad keys with custom sizes
      zero_key:
        what: mx
        where: [zero_key]
        params:
          hotswap: true
          reverse: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{row_net}}"

      plus_key:
        what: mx
        where: [plus_key]
        params:
          hotswap: true
          reverse: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{row_net}}"

      enter_key:
        what: mx
        where: [enter_key]
        params:
          hotswap: true
          reverse: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{row_net}}"

      thumb_switch:
        what: mx
        where: [thumb_bottom]
        params:
          hotswap: true
          reverse: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{row_net}}"

      encoder_left:
        what: rotary
        where: encoder_left
        params:
          from: "{{column_net}}"
          to: "{{row_net}}"
          A: encoder_left_a
          B: encoder_left_b
          C: GND

      encoder_right:
        what: rotary
        where: encoder_right
        params:
          from: "{{column_net}}"
          to: "{{row_net}}"
          A: encoder_right_a
          B: encoder_right_b
          C: GND

      encoder_bottom:
        what: rotary
        where: encoder_bottom
        params:
          from: "{{column_net}}"
          to: "{{row_net}}"
          A: encoder_bottom_a
          B: encoder_bottom_b
          C: GND

      diodes:
        what: diode
        where: [key]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]

      oled_screen:
        what: oled
        where: [oled_screen]
        params:
          side: F
          SDA: P3
          SCL: P2
          VCC: VCC
          GND: GND

      mounting_holes:
        what: infused-kim/mounting_hole
        where: [mount_hole]
        params:
          drill: 2.2

      controller:
        what: promicro
        where: [mcu]
        params:
          orientation: up
          P0: col0
          P1: col1
          P2: SCL
          P3: SDA
          P4: col_thumb
          P5: col_left
          P6: row_thumb
          P7: col_enc_left
          P8: col_enc_right
          P9: col_enc_bottom
          P10: row0
          P14: row1
          P15: row2
          P16: row3
          P21: row4
          P18: row_enc_left
          P19: row_enc_right
          P20: row_enc_bottom

cases:
  case_top:
    - what: outline
      name: switchplate
      extrude: 1.6 # 1.6mm plate thickness

  case_bottom:
    - what: outline
      name: case_outline
      extrude: 10 # 10mm case height
